<?php
/** Don't load directly */
defined( 'ABSPATH' ) || exit;

if ( ! function_exists( 'gulir_register_options_block_classic_1' ) ) {
	function gulir_register_options_block_classic_1() {

		$prefix = 'classic_1_';

		return [
			'id'         => 'gulir_config_section_styling_classic_1',
			'title'      => esc_html__( 'Classic', 'gulir' ),
			'icon'       => 'el el-indent-right',
			'subsection' => true,
			'desc'       => esc_html__( 'These are settings for the Classic layout. They are overridden by "Block Design" (for Elementor pages) and "Blog Design" (for the Blog and Archive pages).', 'gulir' ),
			'fields'     => [
				[
					'id'    => $prefix . 'info',
					'type'  => 'info',
					'class' => 'layout-info',
					'style' => 'success',
					'desc'  => html_entity_decode( '<img src="' . gulir_get_file_uri( 'backend/assets/' . str_replace( '_', '-', rtrim( $prefix, '_' ) ) . '.jpg' ) . '" alt="' . esc_attr__( 'classic', 'gulir' ) . '">' ),
				],
				[
					'id'     => 'section_start_' . $prefix . 'featured',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Featured Image', 'gulir' ),
					'indent' => true,
				],
				[
					'id'          => $prefix . 'crop_size',
					'title'       => esc_html__( 'Featured Image Size', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a featured image size to optimize with the columns setting.', 'gulir' ),
					'type'        => 'select',
					'options'     => gulir_config_crop_size(),
					'default'     => '0',
				],
				[
					'id'     => 'section_end_' . $prefix . 'featured',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_' . $prefix . 'category',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Entry Category', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => $prefix . 'entry_category',
					'title'    => esc_html__( 'Entry Category', 'gulir' ),
					'subtitle' => esc_html__( 'Select a layout for the entry category to display in the post listing.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_extended_entry_category(),
					'default'  => 'bg-1,big',
				],
				[
					'id'       => $prefix . 'hide_category',
					'type'     => 'select',
					'title'    => esc_html__( 'Responsive - Hide Entry Category', 'gulir' ),
					'subtitle' => esc_html__( 'Hide the entry category on tablet and mobile devices.', 'gulir' ),
					'options'  => gulir_config_hide_dropdown(),
					'default'  => '0',
				],
				[
					'id'     => 'section_end_' . $prefix . 'category',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_' . $prefix . 'title',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Post Title', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => $prefix . 'title_tag',
					'title'    => esc_html__( 'Title HTML Tag', 'gulir' ),
					'subtitle' => esc_html__( 'Select a title HTML tag for the post title.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_heading_tag(),
					'default'  => '0',
				],
				[
					'id'     => 'section_end_' . $prefix . 'title',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_' . $prefix . 'meta',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Entry Meta', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => $prefix . 'entry_meta',
					'type'     => 'select',
					'multi'    => true,
					'title'    => esc_html__( 'Entry Meta Tags', 'gulir' ),
					'subtitle' => esc_html__( 'Select the entry meta tags you want to show.', 'gulir' ),
					'desc'     => esc_html__( 'Customize the appearance of the entry meta. Select "Disable" only if you wish to hide the entry meta.', 'gulir' ),
					'options'  => gulir_config_entry_meta_tags(),
					'default'  => [ 'avatar', 'author', 'update' ],
				],

				[
					'id'       => $prefix . 'review',
					'type'     => 'select',
					'title'    => esc_html__( 'Review Meta', 'gulir' ),
					'subtitle' => esc_html__( 'Disable or select setting for entry review meta.', 'gulir' ),
					'options'  => gulir_config_entry_review(),
					'default'  => '1',
				],
				[
					'id'       => $prefix . 'review_meta',
					'type'     => 'select',
					'options'  => gulir_config_review_desc_dropdown( false ),
					'title'    => esc_html__( 'Review Meta Description', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the meta description at the end of the review bar.', 'gulir' ),
					'default'  => '1',
				],
				[
					'id'       => $prefix . 'sponsor_meta',
					'title'    => esc_html__( 'Sponsored Meta', 'gulir' ),
					'subtitle' => esc_html__( 'Replace entry meta with sponsored meta for sponsored posts.', 'gulir' ),
					'type'     => 'switch',
					'default'  => true,
				],
				[
					'id'       => $prefix . 'tablet_hide_meta',
					'type'     => 'select',
					'multi'    => true,
					'title'    => esc_html__( 'Hide Entry Meta on Tablet', 'gulir' ),
					'subtitle' => esc_html__( 'Select the entry meta tags you would like to hide on tablet devices. In case of long meta tags, it would be useful.', 'gulir' ),
					'options'  => gulir_config_entry_meta_tags(),
					'default'  => [],
				],
				[
					'id'       => $prefix . 'mobile_hide_meta',
					'type'     => 'select',
					'multi'    => true,
					'title'    => esc_html__( 'Hide Entry Meta on Mobile', 'gulir' ),
					'subtitle' => esc_html__( 'Select the entry meta tags you would like to hide on mobile devices. In case of long meta tags, it would be useful.', 'gulir' ),
					'options'  => gulir_config_entry_meta_tags(),
					'default'  => [],
				],
				[
					'id'     => 'section_end_' . $prefix . 'meta',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_' . $prefix . 'bookmark',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Bookmark', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => $prefix . 'bookmark',
					'type'     => 'switch',
					'title'    => esc_html__( 'Bookmark Icon', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the bookmark icon.', 'gulir' ),
					'default'  => false,
				],
				[
					'id'     => 'section_end_' . $prefix . 'bookmark',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_' . $prefix . 'format',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Post Format', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => $prefix . 'entry_format',
					'type'     => 'select',
					'title'    => esc_html__( 'Post Format Icon', 'gulir' ),
					'subtitle' => esc_html__( 'Disable or select setting for the post format.', 'gulir' ),
					'options'  => gulir_config_entry_format(),
					'default'  => 'bottom,big',
				],
				[
					'id'     => 'section_end_' . $prefix . 'format',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_' . $prefix . 'excerpt',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Excerpt', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => $prefix . 'excerpt_length',
					'type'     => 'text',
					'class'    => 'small',
					'validate' => 'numeric',
					'title'    => esc_html__( 'Excerpt - Max Length', 'gulir' ),
					'subtitle' => esc_html__( 'select max length of the post excerpt.', 'gulir' ),
					'desc'     => esc_html__( 'Leave this option blank or set 0 to disable.', 'gulir' ),
					'default'  => 30,
				],
				[
					'id'          => $prefix . 'excerpt_source',
					'title'       => esc_html__( 'Excerpt - Source', 'gulir' ),
					'subtitle'    => esc_html__( 'Where to get the post excerpt.', 'gulir' ),
					'description' => esc_html__( 'When you select "use title tagline". if it is empty, it will fallback to the post excerpt or content.', 'gulir' ),
					'type'        => 'select',
					'options'     => gulir_config_excerpt_source(),
					'default'     => 'tagline',
				],
				[
					'id'       => $prefix . 'hide_excerpt',
					'type'     => 'select',
					'title'    => esc_html__( 'Responsive - Hide Excerpt', 'gulir' ),
					'subtitle' => esc_html__( 'Hide the post excerpt on tablet and mobile devices.', 'gulir' ),
					'options'  => gulir_config_hide_dropdown(),
					'default'  => '0',
				],
				[
					'id'     => 'section_end_' . $prefix . 'excerpt',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_' . $prefix . 'readmore',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Read More', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => $prefix . 'readmore',
					'title'    => esc_html__( 'Read More Button', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the read more button.', 'gulir' ),
					'type'     => 'switch',
					'default'  => false,
				],
				[
					'id'     => 'section_end_' . $prefix . 'readmore',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_' . $prefix . 'centered',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Centering', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => $prefix . 'center_mode',
					'type'     => 'switch',
					'title'    => esc_html__( 'Centering Content', 'gulir' ),
					'subtitle' => esc_html__( 'Centering text and elements for the post listing.', 'gulir' ),
					'default'  => false,
				],
				[
					'id'     => 'section_end_' . $prefix . 'centered',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
			],
		];
	}
}