<?php
/** Don't load directly */
defined( 'ABSPATH' ) || exit;

if ( ! function_exists( 'gulir_register_options_color' ) ) {
	function gulir_register_options_color() {

		return [
			'id'     => 'gulir_config_section_color',
			'title'  => esc_html__( 'Global Colors', 'gulir' ),
			'desc'   => esc_html__( 'Customize the website\'s colors.', 'gulir' ),
			'icon'   => 'el el-tint',
			'fields' => [
				[
					'id'     => 'section_start_global_color',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Highlight Elements', 'gulir' ),
					'indent' => true,
				],
				[
					'id'          => 'global_color',
					'title'       => esc_html__( 'Global Highlight Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a global color. This setting applies to all links, menus, category overlays, main pages, and many contrasting elements.', 'gulir' ),
					'description' => esc_html__( 'Recommend choosing a color that contrasts effectively with white text for optimal visibility.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'          => 'dark_global_color',
					'title'       => esc_html__( 'Dark Mode - Global Highlight Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a global color in dark mode.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'     => 'section_end_global_color',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_accent_color',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Dark Accent', 'gulir' ),
					'indent' => true,
				],
				[
					'id'          => 'accent_color',
					'title'       => esc_html__( 'Dark Accent Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a dark accent color for your site, This setting apply to single header background, gradient colors.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'          => 'dark_accent_color',
					'title'       => esc_html__( 'Dark Mode - Dark Accent Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select dark accent color in dark mode.', 'gulir' ),
					'description' => esc_html__( 'Recommend choosing a lighter color than the dark mode background to ensure these elements are clearly visible in dark mode.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'     => 'section_end_accent_color',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_dark_bg_color',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Body Background', 'gulir' ),
					'indent' => true,
				],
				[
					'id'          => 'body_background',
					'title'       => esc_html__( 'Body Background', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a light solid background the website body. Leave blank to set it as the default.', 'gulir' ),
					'description' => esc_html__( 'Recommend choosing a light background to ensure optimal text visibility in the default (light) mode.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'          => 's_body_background',
					'title'       => esc_html__( 'Body Background for Single Post', 'gulir' ),
					'subtitle'    => esc_html__( 'Specify the body background color for single post pages.', 'gulir' ),
					'description' => esc_html__( 'Defaults to the main body background setting if left blank.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'          => 'dark_background',
					'title'       => esc_html__( 'Dark Mode - Body Background', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a dark solid background for dark mode. Leave blank to set it as the default.', 'gulir' ),
					'description' => esc_html__( 'In dark mode, the body background will also apply to single posts.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'     => 'section_end_dark_bg_color',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_button_colors',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Button', 'gulir' ),
					'notice' => [
						esc_html__( 'The settings below will be useful if you want to apply a light background color and dark text to buttons.', 'gulir' ),
						esc_html__( 'The following settings will affect all buttons site-wide in both default and dark modes.', 'gulir' ),
					],
					'indent' => true,
				],
				[
					'id'          => 'btn_primary_color',
					'title'       => esc_html__( 'Primary Color (Background)', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a primary background color for the buttons.', 'gulir' ),
					'description' => esc_html__( 'Leave blank to use the default color based on global colors settings.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
				],
				[
					'id'          => 'btn_accent_color',
					'title'       => esc_html__( 'Accent Color (Text)', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color for the button text.', 'gulir' ),
					'description' => esc_html__( 'Leave blank to use the default color (white).', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
				],
				[
					'id'          => 'btn_primary_hover_color',
					'title'       => esc_html__( 'Hover - Primary Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Set the background color for buttons when hovered.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
				],
				[
					'id'          => 'btn_accent_hover_color',
					'title'       => esc_html__( 'Hover - Accent Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Set the text color for buttons when hovered.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
				],
				[
					'id'     => 'section_end_button_colors',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_mode_switcher',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Mode Switcher', 'gulir' ),
					'subtitle' => esc_html__( 'These settings below will apply to all dark/light mode switchers on the website.', 'gulir' ),
					'indent'   => true,
				],
				[
					'id'          => 'light_switcher_color',
					'title'       => esc_html__( 'Light Switcher - Icon Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color for for the sun icon.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'          => 'light_switcher_bg',
					'title'       => esc_html__( 'Light Switcher - Icon Background', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a background for the sun icon.', 'gulir' ),
					'description' => esc_html__( 'Background settings will not be applied when using the Minimalistic switch style.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
				],
				[
					'id'          => 'light_switcher_slide',
					'title'       => esc_html__( 'Light Switcher - Slide Background', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a background for the slider in light mode.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
				],
				[
					'id'          => 'dark_switcher_color',
					'title'       => esc_html__( 'Dark Switcher - Icon Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color for for the moon icon.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
				],
				[
					'id'          => 'dark_switcher_bg',
					'title'       => esc_html__( 'Dark Switcher - Icon Background', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a background for the moon icon.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
				],
				[
					'id'          => 'dark_switcher_slide',
					'title'       => esc_html__( 'Dark Switcher - Slide Background', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a background for the slider in dark mode.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
				],
				[
					'id'     => 'section_end_mode_switcher',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_bookmark_color',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Bookmark Hovering', 'gulir' ),
					'indent' => true,
				],
				[
					'id'          => 'bookmark_color',
					'title'       => esc_html__( 'Bookmark Hover Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color value when hovering on the bookmark.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'          => 'dark_bookmark_color',
					'title'       => esc_html__( 'Dark Mode - Bookmark Hover Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color value when hovering on the bookmark in dark mode.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'     => 'section_end_bookmark_color',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_review_color',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Review Stars', 'gulir' ),
					'indent' => true,
				],
				[
					'id'          => 'review_color',
					'title'       => esc_html__( 'Background Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a primary background color for the review star icon.', 'gulir' ),
					'description' => esc_html__( 'The default background color is #ffc300.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'          => 'review_icon_color',
					'title'       => esc_html__( 'Icon Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color for the review star icon.', 'gulir' ),
					'description' => esc_html__( 'The default color is white.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'          => 'dark_review_color',
					'title'       => esc_html__( 'Dark Mode - Background Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a primary background color for review star icon in dark mode.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'          => 'dark_review_icon_color',
					'title'       => esc_html__( 'Dark Mode - Icon Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select an icon color for review star icon in dark mode.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'     => 'section_end_review_color',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_sponsor_color',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Sponsor Label', 'gulir' ),
					'indent' => true,
				],
				[
					'id'          => 'sponsor_color',
					'title'       => esc_html__( 'Sponsor Label Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color value for the sponsor label.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'          => 'dark_sponsor_color',
					'title'       => esc_html__( 'Dark Mode - Sponsor Label Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color value for the sponsor label in dark mode.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'     => 'section_end_sponsor_color',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_counter_color',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Popular Counter', 'gulir' ),
					'indent' => true,
				],
				[
					'id'          => 'counter_color',
					'title'       => esc_html__( 'Popular Counter Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color for the counter elements.', 'gulir' ),
					'description' => esc_html__( 'Transparent color is recommended.', 'gulir' ),
					'type'        => 'color_rgba',
				],
				[
					'id'       => 'dark_counter_color',
					'title'    => esc_html__( 'Dark Mode - Popular Counter Color', 'gulir' ),
					'subtitle' => esc_html__( 'Select a color for the counter elements in dark mode.', 'gulir' ),
					'type'     => 'color_rgba',
				],
				[
					'id'     => 'section_end_counter_color',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_live_blog_color',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Live Blogging', 'gulir' ),
					'indent' => true,
				],
				[
					'id'          => 'live_blog_color',
					'title'       => esc_html__( 'Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color for the live blogging icons.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'          => 'dark_live_blog_color',
					'title'       => esc_html__( 'Dark Mode - Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color for the live blogging icons in dark mode.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'     => 'section_end_live_blog_color',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_toc_color',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'TOC, Left Shares & Inline Related', 'gulir' ),
					'indent' => true,
				],
				[
					'id'          => 'toc_bg',
					'title'       => esc_html__( 'Background', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a background color for the table of contents, left share section, and inline related section.', 'gulir' ),
					'description' => esc_html__( 'Recommend choosing a light background to ensure optimal text visibility in the default (light) mode.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'          => 'dark_toc_bg',
					'title'       => esc_html__( 'Dark Mode - Background', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a background color for the table of contents, left share section, and inline related section in dark mode.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'     => 'section_end_toc_color',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_tick_color',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Verified Tick Color', 'gulir' ),
					'indent' => true,
				],
				[
					'id'          => 'author_tick_color',
					'title'       => esc_html__( 'Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Choose a color for the Verified Tick that will appear next to the author name.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
				],
				[
					'id'          => 'dark_author_tick_color',
					'title'       => esc_html__( 'Dark Mode - Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Choose a color for the Verified Tick that will appear next to the author name in dark mode.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
				],
				[
					'id'     => 'section_end_tick_color',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_input_focus_color',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Input Focus Border', 'gulir' ),
					'subtitle' => esc_html__( 'To configure the style for input fields, please navigate to "Theme Design > Input Style".', 'gulir' ),
					'indent'   => true,
				],
				[
					'id'          => 'input_focus_color',
					'title'       => esc_html__( 'Focus Border Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Choose a border color when typing in the input field.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
				],
				[
					'id'     => 'section_end_input_focus_color',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],

			],
		];
	}
}
