<?php
/** Don't load directly */
defined( 'ABSPATH' ) || exit;

if ( ! function_exists( 'gulir_register_options_login' ) ) {
	function gulir_register_options_login() {

		return [
			'id'     => 'gulir_config_section_login_screen',
			'title'  => esc_html__( 'Login', 'gulir' ),
			'desc'   => esc_html__( 'Customize for the login screen and login popup.', 'gulir' ),
			'icon'   => 'el el-wordpress',
			'fields' => [
				[
					'id'       => 'section_start_login_popup',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Popup Sign In', 'gulir' ),
					'subtitle' => esc_html__( 'The popup login is supported for login button and personalized system if need.', 'gulir' ),
					'indent'   => true,
				],
				[
					'id'       => 'disable_login_popup',
					'type'     => 'select',
					'title'    => esc_html__( 'Login Popup Support', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the sign-in popup across the entire website.', 'gulir' ),
					'options'  => [
						'0' => esc_html__( 'Enable', 'gulir' ),
						'1' => esc_html__( 'Disable', 'gulir' ),
					],
					'default'  => '0',
				],
				[
					'id'          => 'login_form_hook',
					'type'        => 'switch',
					'title'       => esc_html__( 'Login_Form Hook', 'gulir' ),
					'subtitle'    => esc_html__( 'Add the "login_form" hook in popup login form for better compatibility with login security plugins.', 'gulir' ),
					'description' => esc_html__( 'This allows third-party plugins to add security checks, such as challenge questions or CAPTCHA, via this hook.', 'gulir' ),
					'required'    => [ 'disable_login_popup', '=', 0 ],
					'default'     => false,
				],
				[
					'id'       => 'header_login_heading',
					'type'     => 'text',
					'title'    => esc_html__( 'Form Heading', 'gulir' ),
					'subtitle' => esc_html__( 'Input a heading for the login form.', 'gulir' ),
					'required' => [ 'disable_login_popup', '=', 0 ],
					'default'  => esc_html__( 'Welcome Back!', 'gulir' ),
				],
				[
					'id'       => 'header_login_description',
					'type'     => 'text',
					'title'    => esc_html__( 'Form Description', 'gulir' ),
					'subtitle' => esc_html__( 'Input a description for the login form. Leave blank to set it as the default.', 'gulir' ),
					'required' => [ 'disable_login_popup', '=', 0 ],
					'default'  => esc_html__( 'Sign in to your account', 'gulir' ),
				],
				[
					'id'          => 'header_login_logo',
					'type'        => 'media',
					'title'       => esc_html__( 'Form Logo', 'gulir' ),
					'subtitle'    => esc_html__( 'Adding a custom logo for the login form. Leave blank to set it as the default.', 'gulir' ),
					'description' => esc_html__( 'Recommended for the logo height is 160px', 'gulir' ),
					'url'         => true,
					'preview'     => true,
					'required'    => [ 'disable_login_popup', '=', 0 ],
				],
				[
					'id'          => 'header_login_dark_logo',
					'type'        => 'media',
					'title'       => esc_html__( 'Dark Mode - Form Logo', 'gulir' ),
					'subtitle'    => esc_html__( 'Adding a custom logo for the login form in dark mode.', 'gulir' ),
					'description' => esc_html__( 'Recommended for the logo height is 160px', 'gulir' ),
					'url'         => true,
					'preview'     => true,
					'required'    => [ 'disable_login_popup', '=', 0 ],
				],
				[
					'id'          => 'login_popup_width',
					'type'        => 'text',
					'class'       => 'small',
					'validate'    => 'numeric',
					'title'       => esc_html__( 'Form Width', 'gulir' ),
					'subtitle'    => esc_html__( 'Specify the maximum width of the login popup in pixels.', 'gulir' ),
					'description' => esc_html__( ' This value determines how wide the popup can expand.', 'gulir' ),
					'default'     => '350',
					'required'    => [ 'disable_login_popup', '=', 0 ],
				],
				[
					'id'     => 'section_end_login_popup',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_login_screen',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Default Login Screen', 'gulir' ),
					'subtitle' => esc_html__( 'This configuration will be effective to the default wp-login.php page.', 'gulir' ),
					'indent'   => true,
				],
				[
					'id'       => 'login_screen_style',
					'title'    => esc_html__( 'Custom Login Screen', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable wp-login.php page style.', 'gulir' ),
					'type'     => 'select',
					'options'  => [
						'1' => esc_html__( 'Enable', 'gulir' ),
						'0' => esc_html__( 'Disable', 'gulir' ),
					],
					'default'  => '0',
				],
				[
					'id'       => 'login_form_position',
					'title'    => esc_html__( 'Login Form Position', 'gulir' ),
					'subtitle' => esc_html__( 'Select a position for the login form.', 'gulir' ),
					'type'     => 'select',
					'options'  => [
						'0' => esc_html__( '- Left -', 'gulir' ),
						'1' => esc_html__( 'Center', 'gulir' ),
						'2' => esc_html__( 'Right', 'gulir' ),
					],
					'required' => [ 'login_screen_style', '=', 1 ],
					'default'  => '0',
				],
				[
					'id'       => 'login_screen_logo',
					'type'     => 'media',
					'url'      => true,
					'preview'  => true,
					'title'    => esc_html__( 'Login Logo', 'gulir' ),
					'subtitle' => esc_html__( 'Upload your logo for the logo screen. This option will override on wordpress logo.', 'gulir' ),
					'required' => [ 'login_screen_style', '=', 1 ],
				],
				[
					'id'          => 'logo_redirect',
					'type'        => 'text',
					'title'       => esc_html__( 'Logo - Destination URL', 'gulir' ),
					'subtitle'    => esc_html__( 'Redirect to this link when clicking on the logo.', 'gulir' ),
					'description' => esc_html__( 'Leave this option blank to redirect to the homepage.', 'gulir' ),
					'required'    => [ 'login_screen_style', '=', 1 ],
				],
				[
					'id'          => 'login_screen_bg',
					'type'        => 'background',
					'transparent' => false,
					'preview'     => true,
					'title'       => esc_html__( 'Login Screen Background', 'gulir' ),
					'subtitle'    => esc_html__( 'Upload your background for the logo screen.', 'gulir' ),
					'default'     => [
						'background-size'       => 'cover',
						'background-attachment' => 'fixed',
						'background-repeat'     => 'no-repeat',
						'background-position'   => 'center center',
					],
					'required'    => [ 'login_screen_style', '=', 1 ],
				],
				[
					'id'          => 'login_color',
					'type'        => 'color',
					'transparent' => false,
					'title'       => esc_html__( 'Login Screen Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color for the login screen.', 'gulir' ),
					'required'    => [ 'login_screen_style', '=', 1 ],
				],
				[
					'id'     => 'section_end_login_screen',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_login_custom',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Frontend Login and Registration Pages', 'gulir' ),
					'notice' => [
						esc_html__( 'Ensure that links are specified as internal links.', 'gulir' ),
						esc_html__( 'These settings define the frontend login and registration pages, which will be effective across the majority of login forms.', 'gulir' ),
						esc_html__( 'You can create your custom frontend login page using the Elementor block "Gulir - Login Form".', 'gulir' ),
					],
					'indent' => true,
				],
				[
					'id'          => 'login_page',
					'type'        => 'text',
					'title'       => esc_html__( 'Custom Login Page URL', 'gulir' ),
					'subtitle'    => esc_html__( 'Enter the URL of your custom login page.', 'gulir' ),
					'placeholder' => 'https://yourwebsite.com/login',
					'description' => esc_html__( 'This page must include the Elementor block "Gulir - Login Form" to create a dedicated login page.', 'gulir' ),
				],
				[
					'id'          => 'login_register',
					'type'        => 'text',
					'title'       => esc_html__( 'Custom Registration Page URL', 'gulir' ),
					'placeholder' => 'https://yourwebsite.com/register',
					'subtitle'    => esc_html__( 'Enter the URL of your custom registration page, if available.', 'gulir' ),
					'description' => esc_html__( 'The registration form can be created using a third-party plugins registration form shortcode, such as WooCommerce or membership plugins.', 'gulir' ),
				],
				[
					'id'          => 'login_page_disable_logged',
					'type'        => 'switch',
					'title'       => esc_html__( 'Redirect Login/Register Page for Logged-In Users', 'gulir' ),
					'subtitle'    => esc_html__( 'Automatically redirects logged-in users to the "Logged-In Redirect URL" specified below when they try to access the custom login or register page.', 'gulir' ),
					'description' => esc_html__( 'Ensure that the "Logged-In Redirect URL" setting below is configured for this setting to function properly.', 'gulir' ),
					'default'     => true,
				],
				[
					'id'          => 'login_redirect',
					'type'        => 'text',
					'title'       => esc_html__( 'Logged-In Redirect URL', 'gulir' ),
					'placeholder' => 'https://yourwebsite.com/profile',
					'subtitle'    => esc_html__( 'Input the URL where users will be redirected after logging in.', 'gulir' ),
					'required'    => [ 'login_page_disable_logged', '=', true ],
				],
				[
					'id'          => 'logout_redirect',
					'type'        => 'text',
					'title'       => esc_html__( 'Logout Redirect URL', 'gulir' ),
					'subtitle'    => esc_html__( 'Enter the URL where users will be redirected after logging out.', 'gulir' ),
					'placeholder' => 'https://yourwebsite.com',
				],
				[
					'id'     => 'section_end_login_custom',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_login_admin_bar',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Admin Bar', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => 'remove_admin_bar',
					'type'     => 'switch',
					'title'    => esc_html__( 'Disable Admin Bar', 'gulir' ),
					'subtitle' => esc_html__( 'Disable admin bar for all users except for Administrators', 'gulir' ),
					'default'  => true,
				],
				[
					'id'       => 'remove_lang_bar',
					'type'     => 'switch',
					'title'    => esc_html__( 'Disable Language Bar', 'gulir' ),
					'subtitle' => esc_html__( 'Disable the language bar in the login screen.', 'gulir' ),
					'default'  => false,
				],
				[
					'id'     => 'section_end_login_admin_bar',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
			],
		];
	}
}
