<?php
/** Don't load directly */
defined( 'ABSPATH' ) || exit;
if ( ! function_exists( 'gulir_register_options_bookmark' ) ) {
	function gulir_register_options_bookmark() {

		return [
			'title' => esc_html__( 'Personalized System', 'gulir' ),
			'id'    => 'gulir_config_section_bookmark',
			'icon'  => 'el el-bookmark',
		];
	}
}
if ( ! function_exists( 'gulir_register_options_bookmark_general' ) ) {
	function gulir_register_options_bookmark_general() {

		return [
			'title'      => esc_html__( 'Global', 'gulir' ),
			'id'         => 'gulir_config_section_bookmark_general',
			'desc'       => esc_html__( 'Customize for the personalized system.', 'gulir' ),
			'icon'       => 'el el-globe',
			'subsection' => true,
			'fields'     => [
				[
					'id'    => 'personalize_icon_info',
					'type'  => 'info',
					'style' => 'info',
					'desc'  => esc_html__( 'By default, bookmark and follow icons are hidden in listing layouts. To display them, you need to enable each icon individually in the block settings.', 'gulir' ),
				],
				[
					'id'     => 'section_start_bookmark_general',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Personalized System', 'gulir' ),
					'notice' => [
						esc_html__( 'PLEASE NOTE: The Personalized System needs to be enabled if you are using Personalized Elementor blocks.', 'gulir' ),
						esc_html__( 'It is recommended to enable the login popup in "Login > Login Popup Supported" if you select "Redirect to Login for Guest Users" for the personalized system.', 'gulir' ),
					],
					'indent' => true,
				],
				[
					'id'          => 'bookmark_system',
					'type'        => 'switch',
					'title'       => esc_html__( 'Personalized System', 'gulir' ),
					'subtitle'    => esc_html__( 'Enable or disable the personalized system.', 'gulir' ),
					'description' => esc_html__( 'This is a global setting. Disabling it will stop all AJAX requests for bookmarks, follows, and history, and will prevent data from being saved to the database.', 'gulir' ),
					'default'     => true,
				],
				[
					'id'     => 'section_end_bookmark_general',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_bookmark_condition',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Conditions', 'gulir' ),
					'required' => [ 'bookmark_system', '=', true ],
					'indent'   => true,
				],
				[
					'id'       => 'bookmark_enable_when',
					'type'     => 'select',
					'title'    => esc_html__( 'Enable When', 'gulir' ),
					'subtitle' => esc_html__( 'Allow or disallow guest users can save posts, follow categories, authors and more.', 'gulir' ),
					'options'  => [
						'0'         => esc_html__( 'All Visitors', 'gulir' ),
						'logged'    => esc_html__( 'Only Logged Users', 'gulir' ),
						'ask_login' => esc_html__( 'Redirect to Login for Guest Users', 'gulir' ),
					],
					'default'  => '0',
				],
				[
					'id'       => 'bookmark_guest_expired',
					'type'     => 'text',
					'class'    => 'small',
					'validate' => 'numeric',
					'title'    => esc_html__( 'Guest Expiration', 'gulir' ),
					'subtitle' => esc_html__( 'Input a value for the number of days after which to clear up database data for guest users who have been inactive.', 'gulir' ),
					'default'  => 14,
				],
				[
					'id'     => 'section_end_bookmark_condition',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_reading_list',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Reading List Template', 'gulir' ),
					'notice'   => [
						esc_html__( 'Firstly, you need to create a page using the "Reading List" template under Pages > Add New to display this feature.', 'gulir' ),
						esc_html__( 'NOTE: If you use the Direct Load method, you need to exclude the Reading List page from caching.', 'gulir' ),
						esc_html__( 'Customize the Reading List template in the "Reading List - Saved, Followed, and Recommended" sections.', 'gulir' ),
					],
					'required' => [ 'bookmark_system', '=', true ],
					'indent'   => true,
				],
				[
					'id'       => 'reading_list_display_mode',
					'type'     => 'select',
					'title'    => esc_html__( 'Display Mode', 'gulir' ),
					'subtitle' => esc_html__( 'Select a display mode for the page that has been assigned the Reading List template.', 'gulir' ),
					'options'  => [
						'0' => esc_html__( '- AJAX -', 'gulir' ),
						'1' => esc_html__( 'Direct', 'gulir' ),
					],
					'default'  => '0',
				],
				[
					'id'     => 'section_end_reading_list',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_bookmark_restricted',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Restricted Information', 'gulir' ),
					'subtitle' => esc_html__( 'This information will be shown in the Personalized blocks in mode "User Saved" if guest bookmarks are disabled.', 'gulir' ),
					'required' => [ 'bookmark_system', '=', true ],
					'indent'   => true,
				],
				[
					'id'          => 'bookmark_restrict_title',
					'type'        => 'textarea',
					'rows'        => 2,
					'title'       => esc_html__( 'Restricted Title', 'gulir' ),
					'subtitle'    => esc_html__( 'Input a restricted title.', 'gulir' ),
					'description' => esc_html__( 'Leave this option blank to remove the feedback!', 'gulir' ),
					'default'     => esc_html__( 'Join our Community', 'gulir' ),
				],
				[
					'id'       => 'bookmark_restrict_desc',
					'type'     => 'textarea',
					'rows'     => 2,
					'title'    => esc_html__( 'Restricted Description', 'gulir' ),
					'subtitle' => esc_html__( 'Input a restricted description.', 'gulir' ),
					'default'  => esc_html__( 'Create an account to save your favorite stories and access them Anytime!', 'gulir' ),
				],
				[
					'id'     => 'section_end_bookmark_restricted',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_bookmark_notification',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Popup Notification', 'gulir' ),
					'required' => [ 'bookmark_system', '=', true ],
					'indent'   => true,
				],
				[
					'id'       => 'bookmark_notification',
					'type'     => 'switch',
					'title'    => esc_html__( 'Popup Notification', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the popup notification when bookmarking.', 'gulir' ),
					'default'  => true,
				],
				[
					'id'     => 'section_end_bookmark_notification',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_follow_archives',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Archives', 'gulir' ),
					'required' => [ 'bookmark_system', '=', true ],
					'indent'   => true,
				],
				[
					'id'       => 'follow_category_header',
					'type'     => 'switch',
					'title'    => esc_html__( 'Follow in The Category Header', 'gulir' ),
					'subtitle' => esc_html__( 'Display the follow button in the header of category pages.', 'gulir' ),
					'default'  => false,
				],
				[
					'id'       => 'follow_tag_header',
					'type'     => 'switch',
					'title'    => esc_html__( 'Follow in The Tag Header', 'gulir' ),
					'subtitle' => esc_html__( 'Display the follow button in the header of tag pages.', 'gulir' ),
					'default'  => false,
				],
				[
					'id'       => 'follow_author_header',
					'type'     => 'switch',
					'title'    => esc_html__( 'Follow in The Author Header', 'gulir' ),
					'subtitle' => esc_html__( 'Display the follow button in the header of author pages.', 'gulir' ),
					'default'  => false,
				],
				[
					'id'       => 'bookmark_author_admin',
					'type'     => 'switch',
					'title'    => esc_html__( 'Show Administrator', 'gulir' ),
					'subtitle' => esc_html__( 'Show or hide the administrator role in the suggestion writers list.', 'gulir' ),
					'default'  => false,
				],
				[
					'id'     => 'section_end_follow_archives',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_bookmark_style',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Bookmark Icon', 'gulir' ),
					'subtitle' => esc_html__( 'The settings below will apply to the "Read It Later" bookmark icon located to the right of the entry bar in the post listing.', 'gulir' ),
					'required' => [ 'bookmark_system', '=', true ],
					'indent'   => true,
				],
				[
					'id'       => 'bookmark_icon_size',
					'type'     => 'text',
					'class'    => 'small',
					'validate' => 'numeric',
					'title'    => esc_html__( 'Bookmark Icon Size', 'gulir' ),
					'subtitle' => esc_html__( 'Input a custom font size (in pixels) for the bookmark icon. Default is body font size.', 'gulir' ),
				],
				[
					'id'       => 'bookmark_icon_size_tablet',
					'type'     => 'text',
					'class'    => 'small',
					'validate' => 'numeric',
					'title'    => esc_html__( 'Tablet Font Size', 'gulir' ),
					'subtitle' => esc_html__( 'Input a custom font size for the bookmark icon on tablet devices.', 'gulir' ),
				],
				[
					'id'       => 'bookmark_icon_size_mobile',
					'type'     => 'text',
					'class'    => 'small',
					'validate' => 'numeric',
					'title'    => esc_html__( 'Mobile Font Size', 'gulir' ),
					'subtitle' => esc_html__( 'Input a custom font size for the bookmark icon on mobile devices.', 'gulir' ),
				],
				[
					'id'     => 'section_end_bookmark_style',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
			],
		];
	}
}
if ( ! function_exists( 'gulir_register_options_reading_list_saved' ) ) {
	function gulir_register_options_reading_list_saved() {

		$prefix = 'saved_';

		return [
			'title'      => esc_html__( 'Reading List - Saved Section', 'gulir' ),
			'id'         => 'gulir_config_section_reading_list',
			'desc'       => esc_html__( 'The settings below will apply to the "Saved Section" of the page that has been assigned the "Reading List" template.', 'gulir' ),
			'icon'       => 'el el-bookmark',
			'subsection' => true,
			'fields'     => [
				[
					'id'    => 'saved_template_info',
					'type'  => 'info',
					'style' => 'info',
					'desc'  => esc_html__( 'You can also place your saved posts anywhere outside the page template with Personalized Elementor blocks.', 'gulir' ),
				],
				[
					'id'     => 'section_start_bookmark_saved',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Saved Header', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => $prefix . 'heading',
					'type'     => 'text',
					'title'    => esc_html__( 'Section Heading', 'gulir' ),
					'subtitle' => esc_html__( 'Input a heading for this section.', 'gulir' ),
					'default'  => esc_html__( 'Reading List', 'gulir' ),
				],
				[
					'id'       => $prefix . 'description',
					'type'     => 'textarea',
					'rows'     => 2,
					'title'    => esc_html__( 'Section Description', 'gulir' ),
					'subtitle' => esc_html__( 'Input description for this section.', 'gulir' ),
					'default'  => esc_html__( 'you\'ll find all saved articles here.', 'gulir' ),
				],
				[
					'id'       => $prefix . 'image',
					'type'     => 'media',
					'url'      => true,
					'preview'  => true,
					'title'    => esc_html__( 'Description Image', 'gulir' ),
					'subtitle' => esc_html__( 'Upload a image for displaying at the top heading. Image height is 60px.', 'gulir' ),
				],
				[
					'id'       => $prefix . 'image_dark',
					'type'     => 'media',
					'url'      => true,
					'preview'  => true,
					'title'    => esc_html__( 'Dark Mode - Description Image', 'gulir' ),
					'subtitle' => esc_html__( 'Upload a image for displaying at the top heading in dark mode.', 'gulir' ),
				],
				[
					'id'       => $prefix . 'pattern',
					'title'    => esc_html__( 'Heading background Style', 'gulir' ),
					'subtitle' => esc_html__( 'Select a background style for this heading.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_archive_header_bg(),
					'default'  => 'dot',
				],
				[
					'id'     => 'section_end_bookmark_saved',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_saved_template',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Template Builder', 'gulir' ),
					'subtitle' => esc_html__( 'Ensure that you have enabled "Use WP Global Query" option under "Template Builder - Global Query > Query Mode" block in your template. This will help the system identify the Reading List section correctly.', 'gulir' ),
					'indent'   => true,
				],
				[
					'id'          => $prefix . 'template',
					'type'        => 'textarea',
					'title'       => esc_html__( 'Template Shortcode', 'gulir' ),
					'subtitle'    => esc_html__( 'Input a "Ruby Template" shortcode to display it as this section layout.', 'gulir' ),
					'placeholder' => '[Ruby_E_Template id="1"]',
					'class'       => 'ruby-template-input',
					'rows'        => 1,
				],
				[
					'id'     => 'section_end_saved_template',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_saved_layout',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Blog Layout', 'gulir' ),
					'required' => [ $prefix . 'template', 'is_empty', '' ],
					'indent'   => true,
				],
				[
					'id'       => $prefix . 'layout',
					'title'    => esc_html__( 'Blog Layout', 'gulir' ),
					'subtitle' => esc_html__( 'Select blog listing layout for the saved pages.', 'gulir' ),
					'type'     => 'image_select',
					'options'  => gulir_config_blog_layout(),
					'default'  => 'grid_1',
				],
				[
					'id'       => $prefix . 'columns',
					'title'    => esc_html__( 'Columns on Desktop', 'gulir' ),
					'subtitle' => esc_html__( 'Select the total number of columns to show per row on desktop devices.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_blog_columns(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'columns_tablet',
					'title'    => esc_html__( 'Columns on Tablet', 'gulir' ),
					'subtitle' => esc_html__( 'Select the total number of columns to show per row on tablet devices.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_blog_columns(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'columns_mobile',
					'title'    => esc_html__( 'Columns on Mobile', 'gulir' ),
					'subtitle' => esc_html__( 'Select the total number of columns to show per row on mobile devices.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_blog_columns( [ '0', '1', '2' ] ),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'column_gap',
					'title'    => esc_html__( 'Column Gap', 'gulir' ),
					'subtitle' => esc_html__( 'Select a spacing between columns.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_blog_column_gap(),
					'default'  => '0',
				],
				[
					'id'     => 'section_end_saved_layout',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_saved_sidebar',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Blog Sidebar', 'gulir' ),
					'required' => [ $prefix . 'template', 'is_empty', '' ],
					'indent'   => true,
				],
				[
					'id'       => $prefix . 'sidebar_position',
					'type'     => 'image_select',
					'title'    => esc_html__( 'Sidebar Position', 'gulir' ),
					'subtitle' => esc_html__( 'Select a sidebar position or disable it for the latest blog section', 'gulir' ),
					'options'  => gulir_config_sidebar_position(),
					'default'  => 'none',
				],
				[
					'id'       => $prefix . 'sidebar_name',
					'type'     => 'select',
					'title'    => esc_html__( 'Assign a Sidebar', 'gulir' ),
					'subtitle' => esc_html__( 'Assign a widget section for the sidebar for the latest blog section if it is enabled.', 'gulir' ),
					'options'  => gulir_config_sidebar_name( false ),
					'default'  => 'gulir_sidebar_default',
				],
				[
					'id'       => $prefix . 'sticky_sidebar',
					'type'     => 'select',
					'title'    => esc_html__( 'Sticky Sidebar', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable sticky sidebar feature.', 'gulir' ),
					'options'  => gulir_config_sticky_dropdown(),
					'default'  => '0',
				],
				[
					'id'     => 'section_end_saved_sidebar',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_saved_design',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Blog Design', 'gulir' ),
					'notice'   => [
						esc_html__( 'The theme\'s default settings are set to use the "Standard Blog Design". However, you can customize these settings using the options below', 'gulir' ),
					],
					'required' => [ $prefix . 'template', 'is_empty', '' ],
					'indent'   => true,
				],
				[
					'id'       => $prefix . 'crop_size',
					'title'    => esc_html__( 'Featured Image Size', 'gulir' ),
					'subtitle' => esc_html__( 'Select a featured image size to optimize with the columns setting.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_crop_size(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'display_ratio',
					'type'     => 'text',
					'title'    => esc_html__( 'Custom Featured Ratio', 'gulir' ),
					'subtitle' => esc_html__( 'Input custom ratio percent (height*100/width) for featured image you would like. e.g. 50', 'gulir' ),
				],
				[
					'id'       => $prefix . 'entry_category',
					'title'    => esc_html__( 'Entry Category', 'gulir' ),
					'subtitle' => esc_html__( 'Select a layout for the entry category to display in the post listing.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_extended_entry_category( true ),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'entry_meta_bar',
					'type'     => 'select',
					'title'    => esc_html__( 'Entry Meta Bar', 'gulir' ),
					'subtitle' => esc_html__( 'Select the entry meta tags you want to show.', 'gulir' ),
					'options'  => gulir_config_entry_meta_bar(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'entry_meta',
					'type'     => 'select',
					'multi'    => true,
					'title'    => esc_html__( 'Entry Meta Tags', 'gulir' ),
					'required' => [ $prefix . 'entry_meta_bar', '=', 'custom' ],
					'subtitle' => esc_html__( 'Customize the appearance of the entry meta. Select "Disable" only if you wish to hide the entry meta.', 'gulir' ),
					'options'  => gulir_config_entry_meta_tags(),
					'default'  => [],
				],
				[
					'id'       => $prefix . 'review',
					'type'     => 'select',
					'title'    => esc_html__( 'Review Meta', 'gulir' ),
					'subtitle' => esc_html__( 'Disable or select setting for entry review meta.', 'gulir' ),
					'options'  => gulir_config_entry_review( true ),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'review_meta',
					'type'     => 'select',
					'title'    => esc_html__( 'Review Meta Description', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the meta description at the end of the review bar.', 'gulir' ),
					'options'  => gulir_config_review_desc_dropdown(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'entry_format',
					'type'     => 'select',
					'title'    => esc_html__( 'Post Format Icon', 'gulir' ),
					'subtitle' => esc_html__( 'Disable or select setting for the post format.', 'gulir' ),
					'options'  => gulir_config_entry_format( true ),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'bookmark',
					'type'     => 'select',
					'title'    => esc_html__( 'Bookmark Icon', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the bookmark icon.', 'gulir' ),
					'options'  => gulir_config_switch_dropdown(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'excerpt',
					'type'     => 'select',
					'title'    => esc_html__( 'Excerpt', 'gulir' ),
					'subtitle' => esc_html__( 'Disable or select settings for the post excerpt.', 'gulir' ),
					'options'  => gulir_config_excerpt_dropdown(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'excerpt_length',
					'type'     => 'text',
					'class'    => 'small',
					'validate' => 'numeric',
					'title'    => esc_html__( 'Excerpt - Max Length', 'gulir' ),
					'required' => [ $prefix . 'excerpt', '=', '1' ],
					'subtitle' => esc_html__( 'select max length of the post excerpt.', 'gulir' ),
					'desc'     => esc_html__( 'Leave this option blank or set 0 to disable.', 'gulir' ),
				],
				[
					'id'          => $prefix . 'excerpt_source',
					'title'       => esc_html__( 'Excerpt - Source', 'gulir' ),
					'subtitle'    => esc_html__( 'Where to get the post excerpt.', 'gulir' ),
					'description' => esc_html__( 'When you select "use title tagline". if it is empty, it will fallback to the post excerpt or content.', 'gulir' ),
					'required'    => [ $prefix . 'excerpt', '=', '1' ],
					'type'        => 'select',
					'options'     => gulir_config_excerpt_source(),
					'default'     => 'tagline',
				],
				[
					'id'       => $prefix . 'readmore',
					'type'     => 'select',
					'title'    => esc_html__( 'Read More Button', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the read more button.', 'gulir' ),
					'options'  => gulir_config_switch_dropdown(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'title_tag',
					'title'    => esc_html__( 'Title HTML Tag', 'gulir' ),
					'subtitle' => esc_html__( 'Select a title HTML tag for the post title.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_heading_tag(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'title_size',
					'title'    => esc_html__( 'Desktop - Title Font Size', 'gulir' ),
					'subtitle' => esc_html__( 'Select a font size (in pixels) for the post title on desktop devices. Leave blank to set it as the default.', 'gulir' ),
					'type'     => 'text',
					'class'    => 'small',
				],
				[
					'id'       => $prefix . 'title_size_tablet',
					'title'    => esc_html__( 'Tablet - Title Font Size', 'gulir' ),
					'subtitle' => esc_html__( 'Select a font size (in pixels) for the post title on tablet devices. Leave blank to set it as the default.', 'gulir' ),
					'type'     => 'text',
					'class'    => 'small',
				],
				[
					'id'       => $prefix . 'title_size_mobile',
					'title'    => esc_html__( 'Mobile - Title Font Size', 'gulir' ),
					'subtitle' => esc_html__( 'Select a font size (in pixels) for the post title on mobile devices. Leave blank to set it as the default.', 'gulir' ),
					'type'     => 'text',
					'class'    => 'small',
				],
				[
					'id'       => $prefix . 'hide_category',
					'type'     => 'select',
					'title'    => esc_html__( 'Responsive - Hide Entry Category', 'gulir' ),
					'subtitle' => esc_html__( 'Hide the entry category on tablet and mobile devices.', 'gulir' ),
					'options'  => [
						'0'      => esc_html__( '- Default -', 'gulir' ),
						'mobile' => esc_html__( 'On Mobile', 'gulir' ),
						'tablet' => esc_html__( 'On Tablet', 'gulir' ),
						'all'    => esc_html__( 'On Tablet & Mobile', 'gulir' ),
						'-1'     => esc_html__( 'Disable', 'gulir' ),
					],
					'default'  => '0',
				],
				[
					'id'          => $prefix . 'tablet_hide_meta',
					'type'        => 'text',
					'title'       => esc_html__( 'Hide Entry Meta on Tablet', 'gulir' ),
					'subtitle'    => esc_html__( 'Input the entry meta tags that you want to hide on tablet devices, separate by comma. e.g. avatar, author...', 'gulir' ),
					'description' => esc_html__( 'Keys include: [avatar, author, date, category, tag, view, comment, update, read, like, bookmark, custom]. Input -1 to re-enable all tags.', 'gulir' ),
					'placeholder' => esc_html__( 'avatar,author', 'gulir' ),
				],
				[
					'id'          => $prefix . 'mobile_hide_meta',
					'type'        => 'text',
					'title'       => esc_html__( 'Hide Entry Meta on Mobile', 'gulir' ),
					'subtitle'    => esc_html__( 'Input the entry meta tags that you want to hide on mobile devices, separate by comma. e.g. avatar, author...', 'gulir' ),
					'description' => esc_html__( 'Keys include: [avatar, author, date, category, tag, view, comment, update, read, like, bookmark, custom]. Input -1 to re-enable all tags.', 'gulir' ),
					'placeholder' => esc_html__( 'avatar,author', 'gulir' ),
				],
				[
					'id'       => $prefix . 'hide_excerpt',
					'type'     => 'select',
					'title'    => esc_html__( 'Responsive - Hide Excerpt', 'gulir' ),
					'subtitle' => esc_html__( 'Hide the post excerpt on tablet and mobile devices.', 'gulir' ),
					'options'  => [
						'0' => esc_html__( '- Default -', 'gulir' ),
						'1' => esc_html__( 'Disable', 'gulir' ),
					],
					'default'  => '0',
				],
				[
					'id'     => 'section_end_saved_design',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
			],
		];
	}
}
if ( ! function_exists( 'gulir_register_options_reading_list_followed' ) ) {
	function gulir_register_options_reading_list_followed() {

		$prefix = 'interest_';

		return [
			'title'      => esc_html__( 'Reading List - Followed', 'gulir' ),
			'id'         => 'gulir_config_section_bookmark_interests',
			'desc'       => esc_html__( 'The settings below will apply to the "Followed Category and Writer Sections" of the page that has been assigned the "Reading List" template.', 'gulir' ),
			'icon'       => 'el el-bookmark',
			'subsection' => true,
			'fields'     => [
				[
					'id'     => 'section_start_interest_general',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'General', 'gulir' ),
					'indent' => true,
				],
				[
					'id'          => $prefix . 'url',
					'type'        => 'text',
					'title'       => esc_html__( 'Redirect More Button', 'gulir' ),
					'subtitle'    => esc_html__( 'Input a custom follow page URL for your customers to add their interests.', 'gulir' ),
					'description' => esc_html__( 'Tip: You can use Elementor to design the destination page for displaying interest-based content.', 'gulir' ),
					'default'     => '#',
				],
				[
					'id'       => $prefix . 'pattern',
					'title'    => esc_html__( 'Background Pattern', 'gulir' ),
					'subtitle' => esc_html__( 'Select a background style for section headings.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_archive_header_bg(),
					'default'  => 'dot',
				],
				[
					'id'     => 'section_end_interest_general',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_interest_category',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Categories Section', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => $prefix . 'category',
					'type'     => 'switch',
					'title'    => esc_html__( 'Categories', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the categories followed by the visitor.', 'gulir' ),
					'default'  => true,
				],
				[
					'id'       => $prefix . 'heading',
					'type'     => 'text',
					'title'    => esc_html__( 'Section Heading', 'gulir' ),
					'subtitle' => esc_html__( 'Input a heading for this section.', 'gulir' ),
					'required' => [ $prefix . 'category', '=', true ],
					'default'  => esc_html__( 'Your Categories', 'gulir' ),
				],
				[
					'id'       => $prefix . 'description',
					'type'     => 'textarea',
					'rows'     => 2,
					'title'    => esc_html__( 'Section Description', 'gulir' ),
					'subtitle' => esc_html__( 'Input description for this section.', 'gulir' ),
					'required' => [ $prefix . 'category', '=', true ],
					'default'  => esc_html__( 'Follow categories that you\'re interested in', 'gulir' ),
				],
				[
					'id'       => $prefix . 'image',
					'type'     => 'media',
					'url'      => true,
					'preview'  => true,
					'title'    => esc_html__( 'Description Image', 'gulir' ),
					'subtitle' => esc_html__( 'Upload a image for displaying at the top heading. Image height is 60px.', 'gulir' ),
					'required' => [ $prefix . 'category', '=', true ],
				],
				[
					'id'       => $prefix . 'image_dark',
					'type'     => 'media',
					'url'      => true,
					'preview'  => true,
					'title'    => esc_html__( 'Dark Mode - Description Image', 'gulir' ),
					'subtitle' => esc_html__( 'Upload a image for displaying at the top heading in dark mode.', 'gulir' ),
					'required' => [ $prefix . 'category', '=', true ],
				],
				[
					'id'     => 'section_end_interest_category',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_interest_author',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Writers Section', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => $prefix . 'author',
					'type'     => 'switch',
					'title'    => esc_html__( 'Writers', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the writers followed by the visitor.', 'gulir' ),
					'default'  => true,
				],
				[
					'id'       => $prefix . 'author_heading',
					'type'     => 'text',
					'title'    => esc_html__( 'Section Heading', 'gulir' ),
					'subtitle' => esc_html__( 'Input a heading for this section.', 'gulir' ),
					'required' => [ $prefix . 'author', '=', true ],
					'default'  => esc_html__( 'Writers Followed', 'gulir' ),
				],
				[
					'id'       => $prefix . 'author_description',
					'type'     => 'textarea',
					'rows'     => 2,
					'title'    => esc_html__( 'Section Description', 'gulir' ),
					'subtitle' => esc_html__( 'Input description for this section.', 'gulir' ),
					'required' => [ $prefix . 'author', '=', true ],
					'default'  => esc_html__( 'Follow writers that you\'re interested in', 'gulir' ),
				],
				[
					'id'       => $prefix . 'author_image',
					'type'     => 'media',
					'url'      => true,
					'preview'  => true,
					'title'    => esc_html__( 'Description Image', 'gulir' ),
					'subtitle' => esc_html__( 'Upload a image for displaying at the top heading. Image height is 60px.', 'gulir' ),
					'required' => [ $prefix . 'author', '=', true ],
				],
				[
					'id'       => $prefix . 'author_image_dark',
					'type'     => 'media',
					'url'      => true,
					'preview'  => true,
					'title'    => esc_html__( 'Dark Mode - Description Image', 'gulir' ),
					'subtitle' => esc_html__( 'Upload a image for displaying at the top heading in dark mode.', 'gulir' ),
					'required' => [ $prefix . 'author', '=', true ],
				],
				[
					'id'     => 'section_end_interest_author',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
			],
		];
	}
}
if ( ! function_exists( 'gulir_register_options_reading_list_recommended' ) ) {
	function gulir_register_options_reading_list_recommended() {

		$prefix = 'recommended_';

		return [
			'title'      => esc_html__( 'Reading List - Recommend', 'gulir' ),
			'id'         => 'gulir_config_section_bookmark_recommended',
			'desc'       => esc_html__( 'Customize the recommended section.', 'gulir' ),
			'icon'       => 'el el-bookmark',
			'subsection' => true,
			'fields'     => [
				[
					'id'     => 'section_start_recommended_general',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'General', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => $prefix . 'interested',
					'type'     => 'switch',
					'title'    => esc_html__( 'Recommended Posts', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the recommended section.', 'gulir' ),
					'default'  => true,
				],
				[
					'id'       => $prefix . 'posts_per_page',
					'title'    => esc_html__( 'Posts per Page', 'gulir' ),
					'subtitle' => esc_html__( 'Select posts per page for this section.', 'gulir' ),
					'type'     => 'text',
					'class'    => 'small',
					'validate' => 'numeric',
					'default'  => 9,
				],
				[
					'id'     => 'section_end_recommended_general',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_recommended_template',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Template Builder', 'gulir' ),
					'subtitle' => esc_html__( 'Ensure "Use WP Global Query" under "Template Builder - Global Query > Query Mode" has been set in a block of your template to help the system understand that it is the recommend section.', 'gulir' ),
					'indent'   => true,
				],
				[
					'id'          => $prefix . 'template',
					'type'        => 'textarea',
					'title'       => esc_html__( 'Template Shortcode', 'gulir' ),
					'subtitle'    => esc_html__( 'Input a "Ruby Template" shortcode to display it as this section layout.', 'gulir' ),
					'desc'        => esc_html__( 'Leave this section blank to use below standard layouts.', 'gulir' ),
					'placeholder' => '[Ruby_E_Template id="1"]',
					'class'       => 'ruby-template-input',
					'rows'        => 1,
				],
				[
					'id'     => 'section_end_recommended_template',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_recommended_heading',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Heading', 'gulir' ),
					'required' => [ $prefix . 'template', 'is_empty', '' ],
					'indent'   => true,
				],
				[
					'id'       => $prefix . 'blog_heading',
					'type'     => 'text',
					'title'    => esc_html__( 'Section Heading', 'gulir' ),
					'subtitle' => esc_html__( 'Input a heading for this section.', 'gulir' ),
					'default'  => esc_html__( 'Recommended for You', 'gulir' ),
				],
				[
					'id'       => $prefix . 'blog_heading_layout',
					'title'    => esc_html__( 'Heading Layout', 'gulir' ),
					'subtitle' => esc_html__( 'Select a heading layout for the heading.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_heading_layout( true ),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'blog_heading_tag',
					'title'    => esc_html__( 'Heading HTML Tag', 'gulir' ),
					'subtitle' => esc_html__( 'Select a HTML tag for this heading.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_heading_tag(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'blog_heading_size',
					'title'    => esc_html__( 'Heading Font Size (Desktop)', 'gulir' ),
					'subtitle' => esc_html__( 'Input a custom font size value for this heading (in pixels) on the desktop. Leave this option blank to set the default.', 'gulir' ),
					'type'     => 'text',
					'class'    => 'small',
					'validate' => 'numeric',
				],
				[
					'id'     => 'section_end_recommended_heading',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_recommended_layout',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Layout', 'gulir' ),
					'subtitle' => esc_html__( 'The theme\'s default settings are set to use the "Standard Blog Design". However, you can customize these settings using the options below', 'gulir' ),
					'required' => [ $prefix . 'template', 'is_empty', '' ],
					'indent'   => true,
				],
				[
					'id'       => $prefix . 'layout',
					'title'    => esc_html__( 'Blog Layout', 'gulir' ),
					'subtitle' => esc_html__( 'Select blog listing layout for this section.', 'gulir' ),
					'type'     => 'image_select',
					'options'  => gulir_config_blog_layout(),
					'default'  => 'grid_1',
				],
				[
					'id'       => $prefix . 'columns',
					'title'    => esc_html__( 'Columns per Row', 'gulir' ),
					'subtitle' => esc_html__( 'Select the total number of columns to show per row on desktop devices.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_blog_columns(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'columns_tablet',
					'title'    => esc_html__( 'Columns on Tablet', 'gulir' ),
					'subtitle' => esc_html__( 'Select the total number of columns to show per row on tablet devices.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_blog_columns(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'columns_mobile',
					'title'    => esc_html__( 'Columns on Mobile', 'gulir' ),
					'subtitle' => esc_html__( 'Select the total number of columns to show per row on mobile devices.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_blog_columns( [ '0', '1', '2' ] ),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'column_gap',
					'title'    => esc_html__( 'Column Gap', 'gulir' ),
					'subtitle' => esc_html__( 'Select a spacing between columns.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_blog_column_gap(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'column_gap',
					'title'    => esc_html__( 'Column Gap', 'gulir' ),
					'subtitle' => esc_html__( 'Select a spacing between columns.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_blog_column_gap(),
					'default'  => '0',
				],
				[
					'id'     => 'section_end_recommended_layout',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_recommended_sidebar',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Blog Sidebar', 'gulir' ),
					'subtitle' => esc_html__( 'The theme\'s default settings are set to use the "Standard Blog Design". However, you can customize these settings using the options below', 'gulir' ),
					'required' => [ $prefix . 'template', 'is_empty', '' ],
					'indent'   => true,
				],
				[
					'id'       => $prefix . 'sidebar_position',
					'type'     => 'image_select',
					'title'    => esc_html__( 'Sidebar Position', 'gulir' ),
					'subtitle' => esc_html__( 'Select a sidebar position or disable it for this section.', 'gulir' ),
					'options'  => gulir_config_sidebar_position(),
					'default'  => 'none',
				],
				[
					'id'       => $prefix . 'sidebar_name',
					'type'     => 'select',
					'title'    => esc_html__( 'Assign a Sidebar', 'gulir' ),
					'subtitle' => esc_html__( 'Assign a widget section for the sidebar for this section if it is enabled.', 'gulir' ),
					'options'  => gulir_config_sidebar_name( false ),
					'default'  => 'gulir_sidebar_default',
				],
				[
					'id'       => $prefix . 'sticky_sidebar',
					'type'     => 'select',
					'title'    => esc_html__( 'Sticky Sidebar', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable sticky sidebar feature.', 'gulir' ),
					'options'  => gulir_config_sticky_dropdown(),
					'default'  => '0',
				],
				[
					'id'     => 'section_end_recommended_sidebar',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_recommended_design',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Blog Design', 'gulir' ),
					'notice'   => [
						esc_html__( 'The theme\'s default settings are set to use the "Standard Blog Design". However, you can customize these settings using the options below', 'gulir' ),
					],
					'required' => [ $prefix . 'template', 'is_empty', '' ],
					'indent'   => true,
				],
				[
					'id'       => $prefix . 'crop_size',
					'title'    => esc_html__( 'Featured Image Size', 'gulir' ),
					'subtitle' => esc_html__( 'Select a featured image size to optimize with the columns setting.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_crop_size(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'display_ratio',
					'type'     => 'text',
					'title'    => esc_html__( 'Custom Featured Ratio', 'gulir' ),
					'subtitle' => esc_html__( 'Input custom ratio percent (height*100/width) for featured image you would like. e.g. 50', 'gulir' ),
				],
				[
					'id'       => $prefix . 'entry_category',
					'title'    => esc_html__( 'Entry Category', 'gulir' ),
					'subtitle' => esc_html__( 'Select a layout for the entry category to display in the post listing.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_extended_entry_category( true ),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'entry_meta_bar',
					'type'     => 'select',
					'title'    => esc_html__( 'Entry Meta Bar', 'gulir' ),
					'subtitle' => esc_html__( 'Select the entry meta tags you want to show.', 'gulir' ),
					'options'  => gulir_config_entry_meta_bar(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'entry_meta',
					'type'     => 'select',
					'multi'    => true,
					'title'    => esc_html__( 'Entry Meta Tags', 'gulir' ),
					'required' => [ $prefix . 'entry_meta_bar', '=', 'custom' ],
					'subtitle' => esc_html__( 'Customize the appearance of the entry meta. Select "Disable" only if you wish to hide the entry meta.', 'gulir' ),
					'options'  => gulir_config_entry_meta_tags(),
					'default'  => [],
				],
				[
					'id'       => $prefix . 'review',
					'type'     => 'select',
					'title'    => esc_html__( 'Review Meta', 'gulir' ),
					'subtitle' => esc_html__( 'Disable or select setting for entry review meta.', 'gulir' ),
					'options'  => gulir_config_entry_review( true ),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'review_meta',
					'type'     => 'select',
					'title'    => esc_html__( 'Review Meta Description', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the meta description at the end of the review bar.', 'gulir' ),
					'options'  => gulir_config_review_desc_dropdown(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'entry_format',
					'type'     => 'select',
					'title'    => esc_html__( 'Post Format Icon', 'gulir' ),
					'subtitle' => esc_html__( 'Disable or select setting for the post format.', 'gulir' ),
					'options'  => gulir_config_entry_format( true ),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'bookmark',
					'type'     => 'select',
					'title'    => esc_html__( 'Bookmark Icon', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the bookmark icon.', 'gulir' ),
					'options'  => gulir_config_switch_dropdown(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'excerpt',
					'type'     => 'select',
					'title'    => esc_html__( 'Excerpt', 'gulir' ),
					'subtitle' => esc_html__( 'Disable or select settings for the post excerpt.', 'gulir' ),
					'options'  => gulir_config_excerpt_dropdown(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'excerpt_length',
					'type'     => 'text',
					'class'    => 'small',
					'validate' => 'numeric',
					'title'    => esc_html__( 'Excerpt - Max Length', 'gulir' ),
					'required' => [ $prefix . 'excerpt', '=', '1' ],
					'subtitle' => esc_html__( 'select max length of the post excerpt.', 'gulir' ),
					'desc'     => esc_html__( 'Leave this option blank or set 0 to disable.', 'gulir' ),
				],
				[
					'id'          => $prefix . 'excerpt_source',
					'title'       => esc_html__( 'Excerpt - Source', 'gulir' ),
					'subtitle'    => esc_html__( 'Where to get the post excerpt.', 'gulir' ),
					'description' => esc_html__( 'When you select "use title tagline". if it is empty, it will fallback to the post excerpt or content.', 'gulir' ),
					'required'    => [ $prefix . 'excerpt', '=', '1' ],
					'type'        => 'select',
					'options'     => gulir_config_excerpt_source(),
					'default'     => 'tagline',
				],
				[
					'id'       => $prefix . 'readmore',
					'type'     => 'select',
					'title'    => esc_html__( 'Read More Button', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the read more button.', 'gulir' ),
					'options'  => gulir_config_switch_dropdown(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'title_tag',
					'title'    => esc_html__( 'Title HTML Tag', 'gulir' ),
					'subtitle' => esc_html__( 'Select a title HTML tag for the post title.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_heading_tag(),
					'default'  => '0',
				],
				[
					'id'       => $prefix . 'title_size',
					'title'    => esc_html__( 'Desktop - Title Font Size', 'gulir' ),
					'subtitle' => esc_html__( 'Select a font size (in pixels) for the post title on desktop devices. Leave blank to set it as the default.', 'gulir' ),
					'type'     => 'text',
					'class'    => 'small',
				],
				[
					'id'       => $prefix . 'title_size_tablet',
					'title'    => esc_html__( 'Tablet - Title Font Size', 'gulir' ),
					'subtitle' => esc_html__( 'Select a font size (in pixels) for the post title on tablet devices. Leave blank to set it as the default.', 'gulir' ),
					'type'     => 'text',
					'class'    => 'small',
				],
				[
					'id'       => $prefix . 'title_size_mobile',
					'title'    => esc_html__( 'Mobile - Title Font Size', 'gulir' ),
					'subtitle' => esc_html__( 'Select a font size (in pixels) for the post title on mobile devices. Leave blank to set it as the default.', 'gulir' ),
					'type'     => 'text',
					'class'    => 'small',
				],
				[
					'id'       => $prefix . 'hide_category',
					'type'     => 'select',
					'title'    => esc_html__( 'Responsive - Hide Entry Category', 'gulir' ),
					'subtitle' => esc_html__( 'Hide the entry category on tablet and mobile devices.', 'gulir' ),
					'options'  => [
						'0'      => esc_html__( '- Default -', 'gulir' ),
						'mobile' => esc_html__( 'On Mobile', 'gulir' ),
						'tablet' => esc_html__( 'On Tablet', 'gulir' ),
						'all'    => esc_html__( 'On Tablet & Mobile', 'gulir' ),
						'-1'     => esc_html__( 'Disable', 'gulir' ),
					],
					'default'  => '0',
				],
				[
					'id'          => $prefix . 'tablet_hide_meta',
					'type'        => 'text',
					'title'       => esc_html__( 'Hide Entry Meta on Tablet', 'gulir' ),
					'subtitle'    => esc_html__( 'Input the entry meta tags that you want to hide on tablet devices, separate by comma. e.g. avatar, author...', 'gulir' ),
					'description' => esc_html__( 'Keys include: [avatar, author, date, category, tag, view, comment, update, read, like, bookmark, custom]. Input -1 to re-enable all tags.', 'gulir' ),
					'placeholder' => esc_html__( 'avatar,author', 'gulir' ),
				],
				[
					'id'          => $prefix . 'mobile_hide_meta',
					'type'        => 'text',
					'title'       => esc_html__( 'Hide Entry Meta on Mobile', 'gulir' ),
					'subtitle'    => esc_html__( 'Input the entry meta tags that you want to hide on mobile devices, separate by comma. e.g. avatar, author...', 'gulir' ),
					'description' => esc_html__( 'Keys include: [avatar, author, date, category, tag, view, comment, update, read, like, bookmark, custom]. Input -1 to re-enable all tags.', 'gulir' ),
					'placeholder' => esc_html__( 'avatar,author', 'gulir' ),
				],
				[
					'id'       => $prefix . 'hide_excerpt',
					'type'     => 'select',
					'title'    => esc_html__( 'Responsive - Hide Excerpt', 'gulir' ),
					'subtitle' => esc_html__( 'Hide the post excerpt on tablet and mobile devices.', 'gulir' ),
					'options'  => [
						'0' => esc_html__( '- Default -', 'gulir' ),
						'1' => esc_html__( 'Disable', 'gulir' ),
					],
					'default'  => '0',
				],
				[
					'id'     => 'section_end_recommended_design',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_recommended_pagination',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Blog Pagination', 'gulir' ),
					'required' => [ $prefix . 'template', 'is_empty', '' ],
					'indent'   => true,
				],
				[
					'id'       => $prefix . 'pagination',
					'title'    => esc_html__( 'Pagination Type', 'gulir' ),
					'subtitle' => esc_html__( 'Select pagination type for this section.', 'gulir' ),
					'type'     => 'select',
					'options'  => [
						'0'               => esc_html__( '- Disable -', 'gulir' ),
						'load_more'       => esc_html__( 'Load More (Ajax)', 'gulir' ),
						'infinite_scroll' => esc_html__( 'Infinite Scroll (Ajax)', 'gulir' ),
					],
					'default'  => '0',
				],
				[
					'id'     => 'section_end_recommended_pagination',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
			],
		];
	}
}
if ( ! function_exists( 'gulir_register_options_user_history' ) ) {
	function gulir_register_options_user_history() {

		return [
			'title'      => esc_html__( 'Read History', 'gulir' ),
			'id'         => 'gulir_config_section_user_history',
			'desc'       => esc_html__( 'Customize the user read history feature.', 'gulir' ),
			'icon'       => 'el el-hourglass',
			'subsection' => true,
			'fields'     => [
				[
					'id'    => 'reading_history_info',
					'type'  => 'info',
					'style' => 'info',
					'desc'  => esc_html__( 'This feature will help your visitors keep track of their browsing history on your website.', 'gulir' ),
				],
				[
					'id'    => 'reading_history_block_info',
					'type'  => 'info',
					'style' => 'info',
					'desc'  => esc_html__( 'You can use the Personalize blocks to build a page for your visitor history via Elementor.', 'gulir' ),
				],
				[
					'id'       => 'reading_history',
					'type'     => 'switch',
					'title'    => esc_html__( 'Read History', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the user read history feature.', 'gulir' ),
					'default'  => false,
				],
				[
					'id'       => 'reading_history_expired',
					'type'     => 'text',
					'validate' => 'numeric',
					'title'    => esc_html__( 'History Expiration', 'gulir' ),
					'subtitle' => esc_html__( 'Automatically remove browsing activity data after x days.', 'gulir' ),
					'required' => [ 'reading_history', '=', true ],
					'default'  => 2,
				],
				[
					'id'       => 'reading_history_title',
					'type'     => 'textarea',
					'rows'     => 1,
					'title'    => esc_html__( 'History Title', 'gulir' ),
					'subtitle' => esc_html__( 'Input a title to display if history not found.', 'gulir' ),
					'default'  => esc_html__( 'Start reading to see your history', 'gulir' ),
					'required' => [ 'reading_history', '=', true ],
				],
				[
					'id'       => 'reading_history_desc',
					'type'     => 'textarea',
					'rows'     => 2,
					'title'    => esc_html__( 'History Description', 'gulir' ),
					'subtitle' => esc_html__( 'Input a description to display if history not found.', 'gulir' ),
					'required' => [ 'reading_history', '=', true ],
					'default'  => esc_html__( 'Stories you\'ve read in the last 48 hours will show up here.', 'gulir' ),
				],
			],
		];
	}
}