<?php
/** Don't load directly */
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! function_exists( 'gulir_register_options_podcast' ) ) {
	function gulir_register_options_podcast() {

		return [
			'id'    => 'gulir_config_section_podcast',
			'title' => esc_html__( 'Ruby Podcast', 'gulir' ),
			'icon'  => 'el el-mic',
		];
	}
}

if ( ! function_exists( 'gulir_register_options_podcast_general' ) ) {
	function gulir_register_options_podcast_general() {

		return [
			'id'         => 'gulir_config_section_podcast_general',
			'title'      => esc_html__( 'General', 'gulir' ),
			'desc'       => esc_html__( 'Customize the podcast post type.', 'gulir' ),
			'icon'       => 'el el-laptop',
			'subsection' => true,
			'fields'     => [
				[
					'id'       => 'section_start_podcast_supported',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Podcast Post Type', 'gulir' ),
					'subtitle' => esc_html__( 'The settings below will not delete exist podcast data in the database.', 'gulir' ),
					'indent'   => true,
				],
				[
					'id'       => 'podcast_supported',
					'title'    => esc_html__( 'Support Podcast', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the podcast post type in your website.', 'gulir' ),
					'type'     => 'switch',
					'default'  => false,
				],
				[
					'id'     => 'section_end_podcast_supported',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_podcast_slugs',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Permalinks', 'gulir' ),
					'indent' => true,
				],
				[
					'id'          => 'podcast_slug',
					'title'       => esc_html__( 'Podcast Slug', 'gulir' ),
					'subtitle'    => esc_html__( 'Input a custom slug for the single podcast.', 'gulir' ),
					'description' => esc_html__( 'Default is "podcast".', 'gulir' ),
					'type'        => 'text',
					'placeholder' => 'podcast',
				],
				[
					'id'          => 'series_slug',
					'title'       => esc_html__( 'Show Slug', 'gulir' ),
					'subtitle'    => esc_html__( 'Input a custom slug for the show.', 'gulir' ),
					'description' => esc_html__( 'Default is "series".', 'gulir' ),
					'type'        => 'text',
					'placeholder' => 'series',
				],
				[
					'id'     => 'section_end_podcast_slugs',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_podcast_display',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Displays', 'gulir' ),
					'subtitle' => esc_html__( 'Allow the podcast episodes to appear on the blog and archives pages.', 'gulir' ),
					'indent'   => true,
				],
				[
					'id'       => 'podcast_blog_included',
					'title'    => esc_html__( 'Include Podcast in The Blog', 'gulir' ),
					'subtitle' => esc_html__( 'The podcast episodes will appear on the blog page (home index).', 'gulir' ),
					'type'     => 'switch',
					'default'  => true,
				],
				[
					'id'       => 'podcast_author_included',
					'title'    => esc_html__( 'Include Podcast in The Author', 'gulir' ),
					'subtitle' => esc_html__( 'The podcast episodes will appear on the author pages.', 'gulir' ),
					'type'     => 'switch',
					'default'  => true,
				],
				[
					'id'       => 'podcast_tag_included',
					'title'    => esc_html__( 'Include Podcast in The Tag', 'gulir' ),
					'subtitle' => esc_html__( 'The podcast episodes will appear on the tag pages.', 'gulir' ),
					'type'     => 'switch',
					'default'  => true,
				],
				[
					'id'     => 'section_end_podcast_display',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_podcast_meta_icons',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Entry Meta', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => 'podcast_meta_play_label',
					'title'    => esc_html__( 'Play/Pause Label', 'gulir' ),
					'subtitle' => esc_html__( 'Show the "Play/Pause" text after the play meta.', 'gulir' ),
					'type'     => 'switch',
					'default'  => true,
				],
				[
					'id'       => 'podcast_meta_author_label',
					'title'    => esc_html__( '"By" Host Label', 'gulir' ),
					'subtitle' => esc_html__( 'Show the "By" text before the host author meta.', 'gulir' ),
					'type'     => 'switch',
					'default'  => false,
				],
				[
					'id'       => 'podcast_meta_duration_label',
					'title'    => esc_html__( 'Duration Label', 'gulir' ),
					'subtitle' => esc_html__( 'Show the "Duration" text before the duration meta.', 'gulir' ),
					'type'     => 'switch',
					'default'  => true,
				],
				[
					'id'     => 'section_end_podcast_meta_icons',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_podcast_inline_ad',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Inline Content Ads', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => 'podcast_inline_ad',
					'type'     => 'switch',
					'title'    => esc_html__( 'Inline Content Ads Supported', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable inline content ads for the single podcast.', 'gulir' ),
					'default'  => true,
				],
				[
					'id'     => 'section_end_podcast_inline_ad',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_podcast_seo',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'SEO Optimized', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => 'single_podcast_markup',
					'type'     => 'switch',
					'title'    => esc_html__( 'Episode Markup', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the default schema markup for the episode.', 'gulir' ),
					'default'  => true,
				],
				[
					'id'     => 'section_end_podcast_seo',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
			],
		];
	}
}

if ( ! function_exists( 'gulir_register_options_podcast_design' ) ) {
	function gulir_register_options_podcast_design() {

		return [
			'id'         => 'gulir_config_section_podcast_styles',
			'title'      => esc_html__( 'Style', 'gulir' ),
			'desc'       => esc_html__( 'Customize the layout and style for the podcast post type.', 'gulir' ),
			'icon'       => 'el el-heart',
			'subsection' => true,
			'fields'     => [
				[
					'id'       => 'section_start_podcast_player',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Podcast Player', 'gulir' ),
					'subtitle' => esc_html__( 'The settings bellow will apply the self-hosted audio player.', 'gulir' ),
					'indent'   => true,
				],
				[
					'id'          => 'podcast_player_color',
					'title'       => esc_html__( 'Player Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color for the self hosted podcast layer.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'          => 'dark_podcast_player_color',
					'title'       => esc_html__( 'Dark Mode - Player Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color for the self hosted podcast layer in dark mode.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'     => 'section_end_podcast_player',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_podcast_icon',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Featured Image Icons', 'gulir' ),
					'notice' => [
						esc_html__( 'The settings bellow will apply only to the search, tags and archive pages.', 'gulir' ),
						esc_html__( 'The microphone icon will appear on the featured image.', 'gulir' ),
					],
					'indent' => true,
				],
				[
					'id'       => 'podcast_socials_overlay',
					'type'     => 'switch',
					'title'    => esc_html__( 'Social Icons', 'gulir' ),
					'subtitle' => esc_html__( 'The listen on socials will appear on the featured image.', 'gulir' ),
					'default'  => true,
				],
				[
					'id'          => 'podcast_custom_icon',
					'type'        => 'media',
					'url'         => true,
					'preview'     => true,
					'title'       => esc_html__( 'Custom Podcast SVG', 'gulir' ),
					'subtitle'    => esc_html__( 'Override the microphone icon with a SVG icon.', 'gulir' ),
					'description' => esc_html__( 'Enable the option in "Theme Design > SVG Upload > SVG Supported" to upload SVG icons.', 'gulir' ),
				],
				[
					'id'          => 'podcast_custom_icon_size',
					'title'       => esc_html__( 'SVG Icon Size', 'gulir' ),
					'subtitle'    => esc_html__( 'Input a custom font size (in px) for your SVG icon.', 'gulir' ),
					'placeholder' => '28',
					'type'        => 'text',
					'class'       => 'small',
				],
				[
					'id'          => 'podcast_custom_size',
					'title'       => esc_html__( 'Icon Size', 'gulir' ),
					'subtitle'    => esc_html__( 'Input a custom font size for the podcast icon.', 'gulir' ),
					'placeholder' => '48',
					'type'        => 'text',
					'class'       => 'small',
				],
				[
					'id'          => 'podcast_icon_bg',
					'title'       => esc_html__( 'Background', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a background color for the podcast icon.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'          => 'podcast_icon_color',
					'title'       => esc_html__( 'Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color for the mic icon.', 'gulir' ),
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
				],
				[
					'id'     => 'section_end_podcast_icon',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_podcast_readmore',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Read More', 'gulir' ),
					'indent' => true,
				],
				[
					'id'          => 'podcast_readmore_label',
					'title'       => esc_html__( 'Read More Label', 'gulir' ),
					'subtitle'    => esc_html__( 'Input the read more label for the podcast post type.', 'gulir' ),
					'placeholder' => 'View Episode',
					'type'        => 'text',
					'default'     => 'View Episode',
				],
				[
					'id'     => 'section_end_podcast_readmore',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
			],
		];
	}
}

if ( ! function_exists( 'gulir_register_options_podcast_single' ) ) {
	function gulir_register_options_podcast_single() {

		return [
			'id'         => 'gulir_config_section_podcast_single',
			'title'      => esc_html__( 'Episode', 'gulir' ),
			'desc'       => esc_html__( 'Manage layout and styles for the episode (single podcast).', 'gulir' ),
			'icon'       => 'el el-list-alt',
			'subsection' => true,
			'fields'     => [
				[
					'id'    => 'info_single_podcast_layout',
					'type'  => 'info',
					'style' => 'warning',
					'desc'  => esc_html__( 'The settings are treated as a global setting. Individual episode settings take priority over them.', 'gulir' ),
				],
				[
					'id'    => 'info_single_podcast_settings',
					'type'  => 'info',
					'style' => 'info',
					'desc'  => esc_html__( 'The single episode will common use some global "Single Post" settings.', 'gulir' ),
				],
				[
					'id'     => 'section_start_single_podcast_layout',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Layout', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => 'single_podcast_layout',
					'type'     => 'image_select',
					'title'    => esc_html__( 'Episode Layout', 'gulir' ),
					'subtitle' => esc_html__( 'Select a layout for the episode.', 'gulir' ),
					'options'  => [
						'1' => [
							'img'   => gulir_get_asset_image( 'single-6.png' ),
							'title' => esc_html__( 'Layout 1', 'gulir' ),
						],
						'2' => [
							'img'   => gulir_get_asset_image( 'single-7.png' ),
							'title' => esc_html__( 'Layout 2', 'gulir' ),
						],
					],
					'default'  => '1',
				],
				[
					'id'          => 'single_podcast_audio_autoplay',
					'type'        => 'switch',
					'title'       => esc_html__( 'Autoplay Audio', 'gulir' ),
					'subtitle'    => esc_html__( 'Autoplay the audio file.', 'gulir' ),
					'description' => esc_html__( 'This setting may not work in some browsers due to the autoplay policies.', 'gulir' ),
					'default'     => false,
				],
				[
					'id'     => 'section_end_single_podcast_layout',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_single_podcast_category',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Entry Show', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => 'single_podcast_entry_category',
					'type'     => 'select',
					'title'    => esc_html__( 'Entry Show', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable entry show info in the episode.', 'gulir' ),
					'options'  => gulir_config_extended_entry_category(),
					'default'  => 'bg-1,big',
				],
				[
					'id'     => 'section_end_single_podcast_category',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_podcast_single_meta',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Entry Meta', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => 'single_podcast_avatar',
					'type'     => 'switch',
					'title'    => esc_html__( 'Big Avatar', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the author avatars before the entry meta bar.', 'gulir' ),
					'default'  => true,
				],
				[
					'id'       => 'single_podcast_entry_meta',
					'type'     => 'select',
					'multi'    => true,
					'title'    => esc_html__( 'Entry Meta Tags', 'gulir' ),
					'subtitle' => esc_html__( 'Organize how you want the entry meta info to appear in the episode.', 'gulir' ),
					'options'  => [
						'avatar'   => esc_html__( 'avatar (Avatar)', 'gulir' ),
						'author'   => esc_html__( 'author (Author)', 'gulir' ),
						'date'     => esc_html__( 'date (Publish Date)', 'gulir' ),
						'category' => esc_html__( 'category (Categories)', 'gulir' ),
						'tag'      => esc_html__( 'tag (Tags)', 'gulir' ),
						'view'     => esc_html__( 'view (Post Views)', 'gulir' ),
						'comment'  => esc_html__( 'comment (Comments)', 'gulir' ),
						'update'   => esc_html__( 'update  (Last Updated)', 'gulir' ),
						'read'     => esc_html__( 'read (Reading Time)', 'gulir' ),
						'like'     => esc_html__( 'like (Like/Dislike)', 'gulir' ),
						'custom'   => esc_html__( 'custom (Custom)', 'gulir' ),
						'duration' => esc_html__( 'duration (Duration)', 'gulir' ),
						'index'    => esc_html__( 'index (Index)', 'gulir' ),
					],
					'default'  => [ 'author', 'index' ],
				],
				[
					'id'          => 'single_podcast_entry_meta_keys',
					'type'        => 'textarea',
					'rows'        => 2,
					'title'       => esc_html__( 'or Custom Key Input', 'gulir' ),
					'subtitle'    => esc_html__( 'This setting is more flexible and allows you to show prefix, suffix, Taxonomy, and custom field value by keys, default keys include: [avatar, author, date, category, tag, view, comment, update, read, like, bookmark, custom, duration, index].', 'gulir' ),
					'description' => esc_html__( 'Prefix & Suffix: You can add a prefix or suffix to a meta using the following format: prefix {meta_key} suffix. For example: author, Categories: {category}, view. You can also allow inline HTML tags such as <i>, <span>, etc.', 'gulir' ),
					'placeholder' => esc_html__( 'author, date', 'gulir' ),
				],
				[
					'id'       => 'single_podcast_meta_author_label',
					'type'     => 'switch',
					'title'    => esc_html__( '"By" Host Label', 'gulir' ),
					'subtitle' => esc_html__( 'Show "by" text before the host meta.', 'gulir' ),
					'default'  => false,
				],
				[
					'id'       => 'single_podcast_author_job',
					'type'     => 'switch',
					'title'    => esc_html__( 'Host Job', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the author job info.', 'gulir' ),
					'default'  => true,
				],
				[
					'id'          => 'single_podcast_meta_date_label',
					'type'        => 'switch',
					'title'       => esc_html__( '"Published & Updated" Date Label', 'gulir' ),
					'subtitle'    => esc_html__( 'Show the label text before the date meta.', 'gulir' ),
					'description' => esc_html__( 'The label only applies if you disable human time (ago format) to avoid SEO issues.', 'gulir' ),
					'default'     => true,
				],
				[
					'id'       => 'single_podcast_tablet_hide_meta',
					'type'     => 'select',
					'multi'    => true,
					'title'    => esc_html__( 'Hide Entry Meta on Tablet', 'gulir' ),
					'subtitle' => esc_html__( 'Select entry meta tags you would like to hide on tablet devices.', 'gulir' ),
					'options'  => gulir_config_entry_meta_tags(),
					'default'  => [],
				],
				[
					'id'       => 'single_podcast_mobile_hide_meta',
					'type'     => 'select',
					'multi'    => true,
					'title'    => esc_html__( 'Hide Entry Meta on Mobile', 'gulir' ),
					'subtitle' => esc_html__( 'Select entry meta tags you would like to hide on mobile devices.', 'gulir' ),
					'options'  => gulir_config_entry_meta_tags(),
					'default'  => [],
				],
				[
					'id'     => 'section_end_podcast_single_meta',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_podcast_single_updated',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Last Updated Date', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => 'single_podcast_updated_meta',
					'type'     => 'switch',
					'title'    => esc_html__( 'Last Updated Date', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the last updated meta.', 'gulir' ),
					'default'  => true,
				],
				[
					'id'          => 'single_podcast_update_format',
					'type'        => 'text',
					'title'       => esc_html__( 'Date Format', 'gulir' ),
					'subtitle'    => esc_html__( 'Custom date format for the last updated meta.', 'gulir' ),
					'placeholder' => 'Y/m/d \a\t g:i A',
				],
				[
					'id'     => 'section_end_podcast_single_updated',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_podcast_single_read',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Reading Time', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => 'single_podcast_min_read',
					'type'     => 'switch',
					'title'    => esc_html__( 'Reading Time', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the reading time meta.', 'gulir' ),
					'default'  => true,
				],
				[
					'id'     => 'section_end_podcast_single_read',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_single_podcast_sidebar',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Sidebar Area', 'gulir' ),
					'indent' => true,
				],
				[
					'id'          => 'single_podcast_sidebar_name',
					'type'        => 'select',
					'title'       => esc_html__( 'Assign a Sidebar', 'gulir' ),
					'subtitle'    => esc_html__( 'Assign a sidebar if you select a episode layout which has a sidebar.', 'gulir' ),
					'description' => esc_html__( 'You can set a sidebar for individual episodes in the post editor.', 'gulir' ),
					'options'     => gulir_config_sidebar_name( false ),
					'default'     => 'gulir_sidebar_default',
				],
				[
					'id'       => 'single_podcast_sidebar_position',
					'type'     => 'image_select',
					'title'    => esc_html__( 'Sidebar Position', 'gulir' ),
					'subtitle' => esc_html__( 'Select a position for the episode sidebar.', 'gulir' ),
					'options'  => gulir_config_sidebar_position(),
					'default'  => 'default',
				],
				[
					'id'       => 'single_podcast_sticky_sidebar',
					'type'     => 'select',
					'title'    => esc_html__( 'Sticky Sidebar', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the sticky sidebar for the episode.', 'gulir' ),
					'options'  => gulir_config_sticky_dropdown(),
					'default'  => '0',
				],
				[
					'id'     => 'section_end_single_podcast_sidebar',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_single_podcast_header',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Site Header', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => 'single_podcast_header_style',
					'type'     => 'select',
					'title'    => esc_html__( 'Header Layout', 'gulir' ),
					'subtitle' => esc_html__( 'Select a site header for the episode.', 'gulir' ),
					'options'  => gulir_config_header_style( true ),
					'default'  => '0',
				],
				[
					'id'          => 'single_podcast_header_template',
					'type'        => 'textarea',
					'title'       => esc_html__( 'Template Shortcode', 'gulir' ),
					'subtitle'    => esc_html__( 'Input a Ruby Template shortcode for displaying as the site header.', 'gulir' ),
					'description' => esc_html__( 'This setting will override on the "Header Layout" setting.', 'gulir' ),
					'placeholder' => '[Ruby_E_Template id="1"]',
					'class'       => 'ruby-template-input',
					'rows'        => 1,
				],
				[
					'id'     => 'section_end_single_podcast_header',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_single_podcast_breadcrumb',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Breadcrumb', 'gulir' ),
					'subtitle' => esc_html__( 'The setting below requests the Navxt plugin, Yoast SEO or Rank Math SEO breadcrumbs to run.', 'gulir' ),
					'indent'   => true,
				],
				[
					'id'       => 'single_podcast_breadcrumb',
					'title'    => esc_html__( 'Episode Breadcrumb', 'gulir' ),
					'subtitle' => esc_html__( 'Enable or disable the breadcrumb bar in the episode.', 'gulir' ),
					'type'     => 'select',
					'options'  => [
						'1' => esc_html__( 'Use Global Setting', 'gulir' ),
						'0' => esc_html__( 'Disable', 'gulir' ),
					],
					'default'  => '1',
				],
				[
					'id'     => 'section_end_single_podcast_breadcrumb',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
			],
		];
	}
}

if ( ! function_exists( 'gulir_register_options_podcast_show' ) ) {
	function gulir_register_options_podcast_show() {

		$prefix = 'series_';

		return [
			'id'         => 'gulir_config_section_show',
			'title'      => esc_html__( 'Show', 'gulir' ),
			'desc'       => esc_html__( 'Manage layout and styles for the show (podcast category).', 'gulir' ),
			'icon'       => 'el el-folder-open',
			'subsection' => true,
			'fields'     => [
				[
					'id'    => $prefix . 'settings_notice',
					'type'  => 'info',
					'style' => 'info',
					'desc'  => esc_html__( 'To edit for individual show, navigate to "Admin Dashboard > Ruby Podcast > Shows > Edit".', 'gulir' ),
				],
				[
					'id'    => $prefix . 'show_layout_notice',
					'type'  => 'info',
					'style' => 'warning',
					'desc'  => esc_html__( 'As default, The grid 3 columns layout will be applied to the shows. You can build a template to assign for the shows in the settings below.', 'gulir' ),
				],
				[
					'id'     => 'section_start_series_site_header',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Site Header', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => $prefix . 'header_style',
					'type'     => 'select',
					'title'    => esc_html__( 'Header Layout', 'gulir' ),
					'subtitle' => esc_html__( 'Select a website header layout for the shows.', 'gulir' ),
					'options'  => gulir_config_header_style( true, true ),
					'default'  => '0',
				],
				[
					'id'          => $prefix . 'nav_style',
					'type'        => 'select',
					'title'       => esc_html__( 'Navigation Bar Style', 'gulir' ),
					'subtitle'    => esc_html__( 'Select navigation bar style for the site header in the shows.', 'gulir' ),
					'description' => esc_html__( 'This setting will apply only to pre-defined headers: 1, 2, 3 and 5.', 'gulir' ),
					'options'     => [
						'0'        => esc_html__( 'Default', 'gulir' ),
						'shadow'   => esc_html__( 'Shadow', 'gulir' ),
						'border'   => esc_html__( 'Bottom Border', 'gulir' ),
						'd-border' => esc_html__( 'Dark Bottom Border', 'gulir' ),
						'none'     => esc_html__( 'None', 'gulir' ),
					],
					'default'     => '0',
				],
				[
					'id'          => $prefix . 'header_template',
					'type'        => 'textarea',
					'title'       => esc_html__( 'Header Template Shortcode', 'gulir' ),
					'subtitle'    => esc_html__( 'Input a Ruby Template shortcode for displaying as the website header for the shows.', 'gulir' ),
					'description' => esc_html__( 'This setting will override on the "Header Layout" setting, Leave it blank if you would like to use the "Header Layout" setting.', 'gulir' ),
					'placeholder' => '[Ruby_E_Template id="1"]',
					'class'       => 'ruby-template-input',
					'rows'        => 1,
				],
				[
					'id'     => 'section_end_series_site_header',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_series_header',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Show Header', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => $prefix . 'category_header',
					'title'    => esc_html__( 'Show Header', 'gulir' ),
					'subtitle' => esc_html__( 'Disable or select a show header layout for the shows.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_category_header(),
					'default'  => '2',
				],
				[
					'id'       => $prefix . 'pattern',
					'title'    => esc_html__( 'Header Background Style', 'gulir' ),
					'subtitle' => esc_html__( 'Select a background style for the show header.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_archive_header_bg(),
					'default'  => 'dot',
				],
				[
					'id'       => $prefix . 'rss',
					'title'    => esc_html__( 'RSS Subscribe', 'gulir' ),
					'subtitle' => esc_html__( 'Show a RSS subscribe button in the show header.', 'gulir' ),
					'type'     => 'switch',
					'default'  => true,
				],
				[
					'id'     => 'section_end_series_header',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_series_template_global',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Global Listing Template', 'gulir' ),
					'subtitle' => esc_html__( 'Ensure "Use WP Global Query" under "Template Builder - Global Query > Query Mode" has been set in a block of your template to help the system understand that it is the main query.', 'gulir' ),
					'indent'   => true,
				],
				[
					'id'          => $prefix . 'template_global',
					'title'       => esc_html__( 'Use Ruby Template for the Post Listing', 'gulir' ),
					'subtitle'    => esc_html__( 'Input a "Ruby Template" shortcode to display as the main blog posts, e.g: [Ruby_E_Template id="1"]', 'gulir' ),
					'description' => esc_html__( 'This setting will be overridden by "Use Ruby Template for the Post Listing" in the individual show setting panel.', 'gulir' ),
					'type'        => 'textarea',
					'placeholder' => '[Ruby_E_Template id="1"]',
					'class'       => 'ruby-template-input',
					'rows'        => 1,
				],
				[
					'id'     => 'section_end_series_template_global',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_series_posts_per_page',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Posts per Page', 'gulir' ),
					'indent' => true,
				],
				[
					'id'          => $prefix . 'posts_per_page',
					'title'       => esc_html__( 'Posts per Page', 'gulir' ),
					'subtitle'    => esc_html__( 'Select posts per page for the shows.', 'gulir' ),
					'description' => esc_html__( 'This setting will override on "Dashboard > Settings > Reading > Blog pages show at most" setting. It will also apply to the "Use Ruby Template for the Post Listing".', 'gulir' ),
					'type'        => 'text',
					'class'       => 'small',
					'validate'    => 'numeric',
				],
				[
					'id'       => $prefix . 'order_by',
					'title'    => esc_html__( 'Order Episodes', 'gulir' ),
					'subtitle' => esc_html__( 'Order by episode index for the shows.', 'gulir' ),
					'info'     => esc_html__( 'As default, the show will order episodes by publish date.', 'gulir' ),
					'type'     => 'select',
					'options'  => [
						'0'               => esc_html__( '- Default -', 'gulir' ),
						'post_index'      => esc_html__( 'Episode Index ASC', 'gulir' ),
						'post_index_desc' => esc_html__( 'Episode Index DECS', 'gulir' ),
					],
					'std'      => '0',
				],
				[
					'id'     => 'section_end_series_posts_per_page',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
			],
		];
	}
}

if ( ! function_exists( 'gulir_register_options_podcast_archive' ) ) {
	function gulir_register_options_podcast_archive() {

		$prefix = 'podcast_archive_';

		return [
			'id'         => 'gulir_config_section_podcast_archive',
			'title'      => esc_html__( 'Archives', 'gulir' ),
			'desc'       => esc_html__( 'Manage layout and styles for the podcast archives.', 'gulir' ),
			'icon'       => 'el el-inbox-box',
			'subsection' => true,
			'fields'     => [
				[
					'id'    => $prefix . 'layout_notice',
					'type'  => 'info',
					'style' => 'warning',
					'desc'  => esc_html__( 'As default, The grid 3 columns layout will be applied to the archives. You can build a template to assign for the archives in the settings below.', 'gulir' ),
				],
				[
					'id'    => 'section_start_podcast_archive_header',
					'type'  => 'section',
					'class' => 'ruby-section-start',
					'title' => esc_html__( 'Archive Header', 'gulir' ),

					'indent' => true,
				],
				[
					'id'       => $prefix . 'pattern',
					'title'    => esc_html__( 'Header Background Style', 'gulir' ),
					'subtitle' => esc_html__( 'Select a background style for the podcast archive header.', 'gulir' ),
					'type'     => 'select',
					'options'  => gulir_config_archive_header_bg(),
					'default'  => 'dot',
				],
				[
					'id'     => 'section_end_podcast_archive_header',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_podcast_archive_template',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Global Listing Template', 'gulir' ),
					'subtitle' => esc_html__( 'Ensure "Use WP Global Query" under "Template Builder - Global Query > Query Mode" has been set in a block of your template to help the system understand that it is the main query.', 'gulir' ),
					'indent'   => true,
				],
				[
					'id'          => $prefix . 'template_global',
					'title'       => esc_html__( 'Use Ruby Template for the Post Listing', 'gulir' ),
					'subtitle'    => esc_html__( 'Input a "Ruby Template" shortcode to display as the main blog posts, e.g: [Ruby_E_Template id="1"]', 'gulir' ),
					'description' => esc_html__( 'This setting will be overridden by "Use Ruby Template for the Post Listing" in the individual show setting panel.', 'gulir' ),
					'type'        => 'textarea',
					'placeholder' => '[Ruby_E_Template id="1"]',
					'class'       => 'ruby-template-input',
					'rows'        => 1,
				],
				[
					'id'     => 'section_end_podcast_archive_template',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_podcast_archive_total',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Posts per Page', 'gulir' ),
					'indent' => true,
				],
				[
					'id'          => $prefix . 'posts_per_page',
					'title'       => esc_html__( 'Posts per Page', 'gulir' ),
					'subtitle'    => esc_html__( 'Select posts per page for the shows.', 'gulir' ),
					'description' => esc_html__( 'This setting will override on "Dashboard > Settings > Reading > Blog pages show at most" setting. It will also apply to the "Use Ruby Template for the Post Listing".', 'gulir' ),
					'type'        => 'text',
					'class'       => 'small',
					'validate'    => 'numeric',
				],
				[
					'id'     => 'section_end_podcast_archive_total',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
			],
		];
	}
}