<?php
/** Don't load directly */
defined( 'ABSPATH' ) || exit;

if ( ! function_exists( 'gulir_register_options_socials' ) ) {
	function gulir_register_options_socials() {

		return [
			'id'     => 'social_theme_options_section_socials',
			'title'  => esc_html__( 'Social Profiles', 'gulir' ),
			'icon'   => 'el el-facebook',
			'desc'   => esc_html__( 'Adding social profiles for your site.', 'gulir' ),
			'fields' => [
				[
					'id'    => 'info_user_socials',
					'type'  => 'info',
					'style' => 'info',
					'desc'  => esc_html__( 'The settings below are used for the your website. To add socials for a user, Navigate to the "Users -> Profile".', 'gulir' ),
				],
				[
					'id'    => 'info_social_profiles',
					'type'  => 'info',
					'style' => 'info',
					'desc'  => esc_html__( 'Leave this field empty to disable social links.', 'gulir' ),
				],
				[
					'id'     => 'section_start_socials',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Social Profiles', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => 'facebook',
					'type'     => 'text',
					'title'    => esc_html__( 'Facebook URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
					'default'  => '#',
				],
				[
					'id'       => 'twitter',
					'type'     => 'text',
					'title'    => esc_html__( 'X (Twitter) URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
					'default'  => '#',
				],
				[
					'id'       => 'youtube',
					'type'     => 'text',
					'title'    => esc_html__( 'Youtube URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
					'default'  => '',
				],
				[
					'id'       => 'googlenews',
					'type'     => 'text',
					'title'    => esc_html__( 'Google News URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
					'default'  => '',
				],
				[
					'id'       => 'instagram',
					'type'     => 'text',
					'title'    => esc_html__( 'Instagram URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'pinterest',
					'type'     => 'text',
					'title'    => esc_html__( 'Pinterest URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
					'default'  => '',
				],
				[
					'id'       => 'tiktok',
					'type'     => 'text',
					'title'    => esc_html__( 'Tiktok URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
					'default'  => '',
				],
				[
					'id'       => 'linkedin',
					'type'     => 'text',
					'title'    => esc_html__( 'LinkedIn URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'medium',
					'type'     => 'text',
					'title'    => esc_html__( 'Medium URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'flipboard',
					'type'     => 'text',
					'title'    => esc_html__( 'Flipboard URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'twitch',
					'type'     => 'text',
					'title'    => esc_html__( 'Twitch URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'steam',
					'type'     => 'text',
					'title'    => esc_html__( 'Steam URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'tumblr',
					'type'     => 'text',
					'title'    => esc_html__( 'Tumblr URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'discord',
					'type'     => 'text',
					'title'    => esc_html__( 'Discord URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'skype',
					'type'     => 'text',
					'title'    => esc_html__( 'Skype URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'snapchat',
					'type'     => 'text',
					'title'    => esc_html__( 'Snapchat URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'quora',
					'type'     => 'text',
					'title'    => esc_html__( 'Quora URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'spotify',
					'type'     => 'text',
					'title'    => esc_html__( 'Spotify URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'apple_podcast',
					'type'     => 'text',
					'title'    => esc_html__( 'Apple Podcasts URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'google_podcast',
					'type'     => 'text',
					'title'    => esc_html__( 'Google Podcasts URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'stitcher',
					'type'     => 'text',
					'title'    => esc_html__( 'Stitcher URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],

				[
					'id'       => 'myspace',
					'type'     => 'text',
					'title'    => esc_html__( 'Myspace URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'bloglovin',
					'type'     => 'text',
					'title'    => esc_html__( 'Bloglovin URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'digg',
					'type'     => 'text',
					'title'    => esc_html__( 'Digg URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'dribbble',
					'type'     => 'text',
					'title'    => esc_html__( 'Dribbble URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'flickr',
					'type'     => 'text',
					'title'    => esc_html__( 'Flickr URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'soundcloud',
					'type'     => 'text',
					'title'    => esc_html__( 'Soundcloud URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'vimeo',
					'type'     => 'text',
					'title'    => esc_html__( 'Vimeo URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'reddit',
					'type'     => 'text',
					'title'    => esc_html__( 'Reddit URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'vkontakte',
					'type'     => 'text',
					'title'    => esc_html__( 'VKontakte URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'telegram',
					'type'     => 'text',
					'title'    => esc_html__( 'Telegram URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'whatsapp',
					'type'     => 'text',
					'title'    => esc_html__( 'Whatsapp URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'truth',
					'type'     => 'text',
					'title'    => esc_html__( 'Truth Social URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'paypal',
					'type'     => 'text',
					'title'    => esc_html__( 'Paypal URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'patreon',
					'type'     => 'text',
					'title'    => esc_html__( 'Patreon Donation URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'threads',
					'type'     => 'text',
					'title'    => esc_html__( 'Threads URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'bluesky',
					'type'     => 'text',
					'title'    => esc_html__( 'Bluesky', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'rss',
					'type'     => 'text',
					'title'    => esc_html__( 'Rss URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'     => 'section_end_socials',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'       => 'section_start_custom_social_1',
					'type'     => 'section',
					'class'    => 'ruby-section-start',
					'title'    => esc_html__( 'Custom Social 1', 'gulir' ),
					'subtitle' => esc_html__( 'Ensure "Theme Design > Font Awesome" setting is enabled in if you use the Font Awesome icons.', 'gulir' ),
					'indent'   => true,
				],
				[
					'id'       => 'custom_social_1_url',
					'type'     => 'text',
					'title'    => esc_html__( 'Custom Social 1 - URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'          => 'custom_social_1_name',
					'type'        => 'text',
					'title'       => esc_html__( 'Custom Social 1 - Name', 'gulir' ),
					'subtitle'    => esc_html__( 'Input the name of the social, e.g. , twitter.', 'gulir' ),
					'placeholder' => esc_html__( 'facebook', 'gulir' ),
				],
				[
					'id'          => 'custom_social_1_icon',
					'type'        => 'text',
					'title'       => esc_html__( 'Custom Social 1 - Icon', 'gulir' ),
					'placeholder' => esc_html__( 'fab fa-facebook', 'gulir' ),
					'subtitle'    => esc_html__( 'Input the name of font icon', 'gulir' ),
				],
				[
					'id'          => 'custom_social_1_color',
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
					'title'       => esc_html__( 'Custom Social 1 - Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color for this social icon.', 'gulir' ),
				],
				[
					'id'     => 'section_end_custom_social_1',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_custom_social_2',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Custom Social 2', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => 'custom_social_2_url',
					'type'     => 'text',
					'title'    => esc_html__( 'Custom Social 2 - URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'custom_social_2_name',
					'type'     => 'text',
					'title'    => esc_html__( 'Custom Social 2 - Name', 'gulir' ),
					'subtitle' => esc_html__( 'Input the name of the social.', 'gulir' ),
				],
				[
					'id'       => 'custom_social_2_icon',
					'type'     => 'text',
					'title'    => esc_html__( 'Custom Social 2 - Icon', 'gulir' ),
					'subtitle' => esc_html__( 'Input the name of font icon.', 'gulir' ),
					'default'  => '',
				],
				[
					'id'          => 'custom_social_2_color',
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
					'title'       => esc_html__( 'Custom Social 2 - Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color for this social icon.', 'gulir' ),
				],
				[
					'id'     => 'section_end_custom_social_2',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
				[
					'id'     => 'section_start_custom_social_3',
					'type'   => 'section',
					'class'  => 'ruby-section-start',
					'title'  => esc_html__( 'Custom Social 3', 'gulir' ),
					'indent' => true,
				],
				[
					'id'       => 'custom_social_3_url',
					'type'     => 'text',
					'title'    => esc_html__( 'Custom Social 3 - URL', 'gulir' ),
					'subtitle' => esc_html__( 'Input your social profile URL.', 'gulir' ),
				],
				[
					'id'       => 'custom_social_3_name',
					'type'     => 'text',
					'title'    => esc_html__( 'Custom Social 3 - Name', 'gulir' ),
					'subtitle' => esc_html__( 'Input the name of the social.', 'gulir' ),
				],
				[
					'id'       => 'custom_social_3_icon',
					'type'     => 'text',
					'title'    => esc_html__( 'Custom Social 3 - Icon', 'gulir' ),
					'subtitle' => esc_html__( 'Input the name of font icon.', 'gulir' ),
					'default'  => '',
				],
				[
					'id'          => 'custom_social_3_color',
					'type'        => 'color',
					'transparent' => false,
					'validate'    => 'color',
					'title'       => esc_html__( 'Custom Social 3 - Color', 'gulir' ),
					'subtitle'    => esc_html__( 'Select a color for this social icon.', 'gulir' ),
				],
				[
					'id'     => 'section_end_custom_social_3',
					'type'   => 'section',
					'class'  => 'ruby-section-end',
					'indent' => false,
				],
			],
		];
	}
}