name: PHP Checks

on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2

      - name: Validate Root composer.json and composer.lock
        run: composer validate --strict

      - name: Validate Plugin composer.json and composer.lock
        run: composer validate --strict --working-dir=mu-plugins/10up-plugin

      - name: Validate Theme composer.json and composer.lock
        run: composer validate --strict --working-dir=themes/10up-theme

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Root dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install Plugin dependencies
        run: composer install --prefer-dist --no-progress --working-dir=mu-plugins/10up-plugin

      - name: Install Theme dependencies
        run: composer install --prefer-dist --no-progress --working-dir=themes/10up-theme

      - name: Run PHPCS
        run: composer lint

      - name: Run PHPStan
        run: composer static
