<?php
/** Don't load directly */
defined( 'ABSPATH' ) || exit;

if ( ! function_exists( 'gulir_get_category_config' ) ) {
	function gulir_get_category_config() {

		return [
			'title'      => esc_html__( 'Gulir Category Settings', 'gulir' ),
			'info'       => esc_html__( 'These settings will apply only to this category and will take priority over other settings in Theme Options > Category.', 'gulir' ),
			'taxonomies' => [ 'category' ],
			'id'         => 'gulir_category_meta',
			'tabs'       => [
				[
					'title' => esc_html__( 'Category Colors', 'gulir' ),
					'id'    => 'entry-category',
					'icon'  => 'dashicons-art',
				],
				[
					'title' => esc_html__( 'Featured Images', 'gulir' ),
					'id'    => 'category-featured',
					'icon'  => 'dashicons-format-gallery',
				],
				[
					'title' => esc_html__( 'Category Header', 'gulir' ),
					'id'    => 'category-header',
					'icon'  => 'dashicons-editor-justify',
				],
				[
					'title' => esc_html__( 'Top Section', 'gulir' ),
					'id'    => 'top-section',
					'icon'  => 'dashicons-align-full-width',
				],
				[
					'title' => esc_html__( 'Listing Queries', 'gulir' ),
					'id'    => 'query',
					'icon'  => 'dashicons-database',
				],
				[
					'title' => esc_html__( 'Listing Template', 'gulir' ),
					'id'    => 'global-template',
					'icon'  => 'dashicons-admin-site',
				],
				[
					'title' => esc_html__( 'Predefined Blog', 'gulir' ),
					'id'    => 'default-blog',
					'icon'  => 'dashicons-text-page',
				],
				[
					'title' => esc_html__( 'Site Header', 'gulir' ),
					'id'    => 'site-header',
					'icon'  => 'dashicons-heading',
				],
				[
					'title' => esc_html__( 'Single Post Layout', 'gulir' ),
					'id'    => 'post-template',
					'icon'  => 'dashicons-format-aside',
				],
			],
			'fields'     => [
				[
					'id'   => 'highlight_color',
					'name' => esc_html__( 'Highlight Color', 'gulir' ),
					'desc' => esc_html__( 'Select a highlight color for the entry icon.', 'gulir' ),
					'info' => esc_html__( 'Default is global color.', 'gulir' ),
					'tab'  => 'entry-category',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'color',
					'name' => esc_html__( 'Accent (Label) Color', 'gulir' ),
					'desc' => esc_html__( 'Select a color for the text label of the entry icon.', 'gulir' ),
					'info' => esc_html__( 'Default is white color.', 'gulir' ),
					'tab'  => 'entry-category',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'meta_color',
					'name' => esc_html__( 'Category Name (for Entry Meta Bar)', 'gulir' ),
					'desc' => esc_html__( 'Select a color for the category name inside the post entry meta bar.', 'gulir' ),
					'info' => esc_html__( 'This color setting applies in the text-only layout inside the meta bar (beside the author, date, reading time, etc.).', 'gulir' ),
					'tab'  => 'entry-category',
					'css'  => 'bold-divider',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'dark_highlight_color',
					'name' => esc_html__( 'Dark Mode - Highlight Color', 'gulir' ),
					'desc' => esc_html__( 'Select a highlight color for the entry icon in dark mode.', 'gulir' ),
					'tab'  => 'entry-category',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'dark_color',
					'name' => esc_html__( 'Dark Mode - Accent (Label) Color', 'gulir' ),
					'desc' => esc_html__( 'Select a color for the text label of the entry icon in dark mode.', 'gulir' ),
					'tab'  => 'entry-category',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'dark_meta_color',
					'name' => esc_html__( 'Dark Mode -  Category Name (for Entry Meta Bar)', 'gulir' ),
					'desc' => esc_html__( 'Select a color for the category name inside the post entry meta bar for dark mode.', 'gulir' ),
					'tab'  => 'entry-category',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'featured_image',
					'name' => esc_html__( 'Featured Images', 'gulir' ),
					'desc' => esc_html__( 'Upload featured images for this category, these images will appear in all "Taxonomies List" blocks and the category header.', 'gulir' ),
					'info' => esc_html__( 'You can set 1 or 2 feature images for a category.', 'gulir' ),
					'tab'  => 'category-featured',
					'type' => 'image',
				],
				[
					'id'   => 'header_style_info',
					'name' => esc_html__( 'Site Header', 'gulir' ),
					'desc' => esc_html__( 'Set up the website header (logo and navigation section) for this category.', 'gulir' ),
					'tab'  => 'site-header',
					'type' => 'info',
				],
				[
					'id'      => 'header_style',
					'name'    => esc_html__( 'Site Header', 'gulir' ),
					'desc'    => esc_html__( 'Select a site header for this category.', 'gulir' ),
					'tab'     => 'site-header',
					'type'    => 'select',
					'options' => gulir_config_header_style( true, true ),
					'std'     => '0',
				],
				[
					'id'          => 'header_template',
					'name'        => esc_html__( 'or Use Ruby Template for Site Header', 'gulir' ),
					'desc'        => esc_html__( 'Input a Ruby Template shortcode for displaying as the website header for this category.', 'gulir' ),
					'info'        => esc_html__( 'This setting will override all "Header Layout" settings. Leave it blank to disable.', 'gulir' ),
					'tab'         => 'site-header',
					'type'        => 'textarea',
					'input_class' => 'ruby-template-input',
					'placeholder' => '[Ruby_E_Template id="1"]',
					'rows'        => 1,
					'std'         => '',
				],
				[
					'id'   => 'category_header_info',
					'name' => esc_html__( 'Category Header', 'gulir' ),
					'desc' => esc_html__( 'This section contains the category name and description, located below the site header.', 'gulir' ),
					'tab'  => 'category-header',
					'type' => 'info',
				],
				[
					'id'      => 'category_header',
					'name'    => esc_html__( 'Category Header', 'gulir' ),
					'desc'    => esc_html__( 'Select a category header layout.', 'gulir' ),
					'tab'     => 'category-header',
					'type'    => 'select',
					'options' => gulir_config_category_header( true ),
					'std'     => '0',
				],
				[
					'id'      => 'pattern',
					'name'    => esc_html__( 'Background Pattern', 'gulir' ),
					'desc'    => esc_html__( 'Select a pattern style for the header background.', 'gulir' ),
					'tab'     => 'category-header',
					'type'    => 'select',
					'options' => gulir_config_archive_header_bg( true ),
					'std'     => '0',
				],
				[
					'id'      => 'breadcrumb',
					'name'    => esc_html__( 'Breadcrumb', 'gulir' ),
					'desc'    => esc_html__( 'Enable or disable the breadcrumb in this category header.', 'gulir' ),
					'tab'     => 'category-header',
					'type'    => 'select',
					'options' => [
						'0'  => esc_html__( '- Default -', 'gulir' ),
						'1'  => esc_html__( 'Use Global Setting', 'gulir' ),
						'-1' => esc_html__( 'Disable', 'gulir' ),
					],
					'std'     => '0',
				],
				[
					'id'      => 'subcategory',
					'name'    => esc_html__( 'Subcategories List', 'gulir' ),
					'desc'    => esc_html__( 'Enable or disable the display of subcategories in this category header.', 'gulir' ),
					'tab'     => 'category-header',
					'type'    => 'select',
					'options' => [
						'0'  => esc_html__( '- Default -', 'gulir' ),
						'1'  => esc_html__( 'Enable', 'gulir' ),
						'-1' => esc_html__( 'Disable', 'gulir' ),
					],
					'std'     => '0',
				],
				[
					'id'          => 'posts_per_page',
					'name'        => esc_html__( 'Posts per Page', 'gulir' ),
					'desc'        => esc_html__( 'Enter the number of posts to display per page for this category.', 'gulir' ),
					'info'        => esc_html__( 'This setting will apply to this category for both the Ruby Template and predefined layouts.', 'gulir' ),
					'tab'         => 'query',
					'placeholder' => '10',
					'type'        => 'text',
					'classes'     => 'small',
					'std'         => '',
				],
				[
					'id'          => 'tag_not_in',
					'name'        => esc_html__( 'Exclude Tags Slug', 'gulir' ),
					'desc'        => esc_html__( 'Remove posts with these tags from the global blog query.', 'gulir' ),
					'info'        => esc_html__( 'Enter tag slugs, separated by commas.', 'gulir' ),
					'placeholder' => 'tag1,tag2,tag3',
					'tab'         => 'query',
					'type'        => 'text',
					'std'         => '',
				],
				[
					'id'   => 'category_top_section_info',
					'name' => esc_html__( 'Top Featured Section', 'gulir' ),
					'desc' => esc_html__( 'This section is located below the category header and helps you build the top featured posts for this category page. You can also create a custom category header if you choose to disable the predefined one.', 'gulir' ),
					'tab'  => 'top-section',
					'type' => 'info',
				],
				[
					'id'          => 'template',
					'name'        => esc_html__( 'Template Shortcode', 'gulir' ),
					'desc'        => esc_html__( 'Input a "Ruby Template" shortcode to embed it after the category header.', 'gulir' ),
					'info'        => esc_html__( 'It will display under the category header, e.g. [Ruby_E_Template id="1"]', 'gulir' ),
					'tab'         => 'top-section',
					'type'        => 'textarea',
					'input_class' => 'ruby-template-input',
					'placeholder' => '[Ruby_E_Template id="1"]',
					'rows'        => 1,
					'std'         => '',
				],
				[
					'id'      => 'template_display',
					'name'    => esc_html__( 'Display Condition', 'gulir' ),
					'desc'    => esc_html__( 'Choose where the template should appear: on the first page only or on all pages.', 'gulir' ),
					'tab'     => 'top-section',
					'type'    => 'select',
					'options' => [
						'0' => esc_html__( '- Default -', 'gulir' ),
						'1' => esc_html__( 'Show in the first page', 'gulir' ),
						'2' => esc_html__( 'Show in all pages', 'gulir' ),
					],
					'std'     => '0',
				],
				[
					'id'      => 'layout',
					'name'    => esc_html__( 'Predefined Layout', 'gulir' ),
					'desc'    => esc_html__( 'Select a predefined layout for displaying the latest posts in this category.', 'gulir' ),
					'info'    => esc_html__( 'Use "Predefined Blog" section for additional configuration if you choose a layout with this setting.', 'gulir' ),
					'tab'     => 'global-template',
					'type'    => 'select',
					'options' => [
						'0'            => esc_html__( '- Default from Theme Options -', 'gulir' ),
						'classic_1'    => esc_html__( 'Classic', 'gulir' ),
						'grid_1'       => esc_html__( 'Grid 1', 'gulir' ),
						'grid_2'       => esc_html__( 'Grid 2', 'gulir' ),
						'grid_box_1'   => esc_html__( 'Boxed Grid 1', 'gulir' ),
						'grid_box_2'   => esc_html__( 'Boxed Grid 2', 'gulir' ),
						'grid_small_1' => esc_html__( 'Small Grid', 'gulir' ),
						'list_1'       => esc_html__( 'List 1', 'gulir' ),
						'list_2'       => esc_html__( 'List 2', 'gulir' ),
						'list_box_1'   => esc_html__( 'Boxed List 1', 'gulir' ),
						'list_box_2'   => esc_html__( 'Boxed List 2', 'gulir' ),
					],
					'std'     => '0',
				],
				[
					'id'          => 'template_global',
					'name'        => esc_html__( 'or Use Ruby Template for Post Listing', 'gulir' ),
					'desc'        => esc_html__( 'Enter a "Ruby Template" shortcode here. This setting will take priority over all other settings.', 'gulir' ),
					'info'        => esc_html__( 'Create a blog listing layout with Ruby Template via Elementor page builder and assign the template shortcode here to create your own layout.', 'gulir' ),
					'tab'         => 'global-template',
					'type'        => 'textarea',
					'input_class' => 'ruby-template-input',
					'placeholder' => '[Ruby_E_Template id="1"]',
					'rows'        => 1,
					'std'         => '',
				],
				[
					'id'   => 'predefined_blog_info',
					'name' => esc_html__( 'Predefined Blog', 'gulir' ),
					'desc' => esc_html__( 'This settings panel is used to configure the post listing layout when a Predefined Layout is set for this category. It will not be available when using a Ruby Template to build the category pages, as you can control everything via Elementor if you use the template builder.', 'gulir' ),
					'tab'  => 'default-blog',
					'type' => 'info',
				],
				[
					'id'          => 'blog_heading',
					'name'        => esc_html__( 'Heading', 'gulir' ),
					'desc'        => esc_html__( 'Input a heading for the post listing.', 'gulir' ),
					'info'        => esc_html__( 'Allow the {archive} dynamic tag. Refer the documentation for further information.', 'gulir' ),
					'placeholder' => esc_html__( 'Latest {archive} News', 'gulir' ),
					'tab'         => 'default-blog',
					'type'        => 'text',
					'std'         => '',
				],
				[
					'id'      => 'blog_heading_layout',
					'name'    => esc_html__( 'Heading Layout', 'gulir' ),
					'desc'    => esc_html__( 'Select a heading layout for the heading.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => gulir_config_heading_layout( true ),
					'std'     => '',
				],
				[
					'id'      => 'blog_heading_tag',
					'name'    => esc_html__( 'Heading HTML Tag', 'gulir' ),
					'desc'    => esc_html__( 'Select a HTML tag for this heading.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => gulir_config_heading_tag(),
					'std'     => '',
				],
				[
					'id'      => 'blog_heading_size',
					'name'    => esc_html__( 'Heading Font Size (Desktop)', 'gulir' ),
					'desc'    => esc_html__( 'Input a custom font size value for this heading (in pixels) on the desktop.', 'gulir' ),
					'info'    => esc_html__( 'Navigate to "Theme Options > Heading Design" for more settings.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'text',
					'classes' => 'small',
					'std'     => '',
				],
				[
					'id'   => 'column_info',
					'name' => esc_html__( 'Post Listing - Columns', 'gulir' ),
					'tab'  => 'default-blog',
					'type' => 'info',
				],
				[
					'id'      => 'columns',
					'name'    => esc_html__( 'Columns on Desktop', 'gulir' ),
					'desc'    => esc_html__( 'Select columns for the latest blog listing on desktop device.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => gulir_config_blog_columns(),
					'std'     => '0',
				],
				[
					'id'      => 'columns_tablet',
					'name'    => esc_html__( 'Columns on Tablet', 'gulir' ),
					'desc'    => esc_html__( 'Select columns for the latest blog listing on tablet devices.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => gulir_config_blog_columns(),
					'std'     => '0',
				],
				[
					'id'      => 'columns_mobile',
					'name'    => esc_html__( 'Columns on Mobile', 'gulir' ),
					'desc'    => esc_html__( 'Select columns for the latest blog listing on mobile devices.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => gulir_config_blog_columns( [ '0', '1', '2' ] ),
					'std'     => '0',
				],
				[
					'id'      => 'column_gap',
					'name'    => esc_html__( 'Column Gap', 'gulir' ),
					'desc'    => esc_html__( 'Select a spacing between columns.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => gulir_config_blog_column_gap(),
					'std'     => '0',
				],
				[
					'id'   => 'pagination_info',
					'name' => esc_html__( 'Post Listing - Pagination', 'gulir' ),
					'tab'  => 'default-blog',
					'type' => 'info',
				],
				[
					'id'      => 'pagination',
					'name'    => esc_html__( 'Pagination Type', 'gulir' ),
					'desc'    => esc_html__( 'Select pagination type for this category.', 'gulir' ),
					'info'    => esc_html__( 'This setting will be not available if you use "Use Ruby Template for the Post Listing" to build the blog listing.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => gulir_config_blog_pagination( true ),
					'std'     => '0',
				],
				[
					'id'   => 'sidebar_info',
					'name' => esc_html__( 'Post Listing - Sidebar', 'gulir' ),
					'tab'  => 'default-blog',
					'type' => 'info',
				],
				[
					'id'      => 'sidebar_position',
					'name'    => esc_html__( 'Sidebar Position', 'gulir' ),
					'desc'    => esc_html__( 'Select a position for the latest blog sidebar.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => gulir_config_category_sidebar_position(),
					'std'     => '0',
				],
				[
					'id'      => 'sidebar_name',
					'name'    => esc_html__( 'Assign a Sidebar', 'gulir' ),
					'desc'    => esc_html__( 'Assign a blog sidebar for this category.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => gulir_config_sidebar_name(),
					'std'     => '0',
				],
				[
					'id'      => 'sticky_sidebar',
					'name'    => esc_html__( 'Sticky Sidebar', 'gulir' ),
					'desc'    => esc_html__( 'Making this sidebar permanently visible when scrolling up and down.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => [
						'0'  => esc_html__( '- Default -', 'gulir' ),
						'1'  => esc_html__( 'Sticky Sidebar', 'gulir' ),
						'2'  => esc_html__( 'Sticky Last Widget', 'gulir' ),
						'-1' => esc_html__( 'Disable', 'gulir' ),
					],
					'std'     => '0',
				],
				[
					'id'   => 'design_featured_image',
					'name' => esc_html__( 'Featured Image', 'gulir' ),
					'tab'  => 'default-blog',
					'type' => 'info',
				],
				[
					'id'      => 'crop_size',
					'name'    => esc_html__( 'Featured Image Size', 'gulir' ),
					'desc'    => esc_html__( 'Select a crop size for the featured image to displaying in this category.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => gulir_config_crop_size(),
					'std'     => '0',
				],
				[
					'id'          => 'display_ratio',
					'name'        => esc_html__( 'Custom Featured Ratio', 'gulir' ),
					'desc'        => esc_html__( 'Input custom ratio percent (height*100/width) for featured image you would like. e.g. 50', 'gulir' ),
					'tab'         => 'default-blog',
					'type'        => 'text',
					'placeholder' => '50',
					'classes'     => 'small',
					'std'         => '',
				],
				[
					'id'   => 'design_entry_meta',
					'name' => esc_html__( 'Entry Category', 'gulir' ),
					'tab'  => 'default-blog',
					'type' => 'info',
				],
				[
					'id'      => 'hide_category',
					'name'    => esc_html__( 'Responsive - Hide Entry Category', 'gulir' ),
					'desc'    => esc_html__( 'Hide the entry category on tablet and mobile devices.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => [
						'0'      => esc_html__( '- Default -', 'gulir' ),
						'mobile' => esc_html__( 'On Mobile', 'gulir' ),
						'tablet' => esc_html__( 'On Tablet', 'gulir' ),
						'all'    => esc_html__( 'On Tablet & Mobile', 'gulir' ),
						'-1'     => esc_html__( 'Disable', 'gulir' ),
					],
					'std'     => '0',
				],
				[
					'id'   => 'design_entry_title',
					'name' => esc_html__( 'Post Title', 'gulir' ),
					'tab'  => 'default-blog',
					'type' => 'info',
				],
				[
					'id'      => 'title_tag',
					'name'    => esc_html__( 'Title HTML Tag', 'gulir' ),
					'desc'    => esc_html__( 'Select a title HTML tag for the post title.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => gulir_config_heading_tag(),
					'std'     => 0,
				],
				[
					'id'      => 'title_size',
					'name'    => esc_html__( 'Desktop - Title Font Size', 'gulir' ),
					'desc'    => esc_html__( 'Select a font size (in pixels) for the post title on desktop devices.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'text',
					'classes' => 'small',
					'std'     => '',
				],
				[
					'id'      => 'title_size_tablet',
					'name'    => esc_html__( 'Tablet - Title Font Size', 'gulir' ),
					'desc'    => esc_html__( 'Select a font size (in pixels) for the post title on tablet devices.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'text',
					'classes' => 'small',
					'std'     => '',
				],
				[
					'id'      => 'title_size_mobile',
					'name'    => esc_html__( 'Mobile - Title Font Size', 'gulir' ),
					'desc'    => esc_html__( 'Select a font size (in pixels) for the post title on mobile devices.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'text',
					'classes' => 'small',
					'std'     => '',
				],
				[
					'id'   => 'design_entry_meta',
					'name' => esc_html__( 'Entry Meta', 'gulir' ),
					'tab'  => 'default-blog',
					'type' => 'info',
				],
				[
					'id'      => 'entry_meta_bar',
					'name'    => esc_html__( 'Entry Meta Bar', 'gulir' ),
					'desc'    => esc_html__( 'Select the entry meta tags you want to show.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => [
						'0'      => esc_html__( '- Default -', 'gulir' ),
						'-1'     => esc_html__( 'Disable', 'gulir' ),
						'custom' => esc_html__( 'Use Custom Below', 'gulir' ),
					],
					'std'     => '0',
				],
				[
					'id'          => 'entry_meta',
					'type'        => 'text',
					'name'        => esc_html__( 'Entry Meta Tags', 'gulir' ),
					'desc'        => esc_html__( 'Input entry meta tags to show.', 'gulir' ),
					'info'        => esc_html__( 'Separated by commas, Keys include: [author, date, category, tag, view, comment, update, read, custom]', 'gulir' ),
					'tab'         => 'default-blog',
					'placeholder' => esc_html__( 'avatar,author,update', 'gulir' ),
					'std'         => '',
				],
				[
					'id'      => 'review',
					'name'    => esc_html__( 'Review Meta', 'gulir' ),
					'desc'    => esc_html__( 'Disable or select setting for entry review meta.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => gulir_config_entry_review( true ),
					'std'     => '0',
				],
				[
					'id'      => 'review_meta',
					'name'    => esc_html__( 'Review Meta Description', 'gulir' ),
					'desc'    => esc_html__( 'Enable or disable the meta description at the end of the review bar.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => gulir_config_review_desc_dropdown(),
					'std'     => '0',
				],
				[
					'id'          => 'tablet_hide_meta',
					'name'        => esc_html__( 'Hide Entry Meta on Tablet', 'gulir' ),
					'desc'        => esc_html__( 'Input the entry meta tags that you want to hide on tablet devices.', 'gulir' ),
					'info'        => esc_html__( 'Separate by comma. e.g. avatar, author... If you want to re-enable all metas input "-1".', 'gulir' ),
					'tab'         => 'default-blog',
					'type'        => 'text',
					'placeholder' => esc_html__( 'avatar,author', 'gulir' ),
					'default'     => '',
				],
				[
					'id'          => 'mobile_hide_meta',
					'name'        => esc_html__( 'Hide Entry Meta on Mobile', 'gulir' ),
					'desc'        => esc_html__( 'Input the entry meta tags that you want to hide on mobile devices.', 'gulir' ),
					'info'        => esc_html__( 'Separate by comma. e.g. avatar, author... If you want to re-enable all metas input "-1".', 'gulir' ),
					'tab'         => 'default-blog',
					'type'        => 'text',
					'placeholder' => esc_html__( 'avatar,author', 'gulir' ),
					'default'     => '',
				],
				[
					'id'   => 'design_entry_bookmark',
					'name' => esc_html__( 'Bookmark', 'gulir' ),
					'tab'  => 'default-blog',
					'type' => 'info',
				],
				[
					'id'      => 'bookmark',
					'name'    => esc_html__( 'Bookmark Icon', 'gulir' ),
					'desc'    => esc_html__( 'Enable or disable the bookmark icon.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => gulir_config_switch_dropdown(),
					'std'     => '0',
				],
				[
					'id'   => 'design_entry_format',
					'name' => esc_html__( 'Post Format', 'gulir' ),
					'tab'  => 'default-blog',
					'type' => 'info',
				],
				[
					'id'      => 'entry_format',
					'name'    => esc_html__( 'Post Format Icon', 'gulir' ),
					'desc'    => esc_html__( 'Disable or select setting for the post format.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => gulir_config_entry_format( true ),
					'std'     => '0',
				],
				[
					'id'   => 'design_entry_excerpt',
					'name' => esc_html__( 'Excerpt', 'gulir' ),
					'tab'  => 'default-blog',
					'type' => 'info',
				],
				[
					'id'      => 'excerpt',
					'name'    => esc_html__( 'Excerpt', 'gulir' ),
					'desc'    => esc_html__( 'Select settings for the post excerpt.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => [
						'0' => esc_html__( '- Default -', 'gulir' ),
						'1' => esc_html__( 'Custom Settings Below', 'gulir' ),
					],
					'std'     => '0',
				],
				[
					'id'      => 'excerpt_length',
					'name'    => esc_html__( 'Excerpt - Max Length', 'gulir' ),
					'desc'    => esc_html__( 'select max length of the post excerpt.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'text',
					'classes' => 'small',
					'std'     => '0',
				],
				[
					'id'          => 'excerpt_source',
					'name'        => esc_html__( 'Excerpt - Source', 'gulir' ),
					'desc'        => esc_html__( 'Where to get the post excerpt.', 'gulir' ),
					'description' => esc_html__( 'When you select "use title tagline". if it is empty, it will fallback to the post excerpt or content.', 'gulir' ),
					'tab'         => 'default-blog',
					'type'        => 'select',
					'options'     => gulir_config_excerpt_source(),
					'std'         => 'tagline',
				],
				[
					'id'      => 'hide_excerpt',
					'name'    => esc_html__( 'Responsive - Hide Excerpt', 'gulir' ),
					'desc'    => esc_html__( 'Hide the post excerpt on tablet and mobile devices.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => [
						'0'      => esc_html__( 'Default from Category Settings', 'gulir' ),
						'mobile' => esc_html__( 'On Mobile', 'gulir' ),
						'tablet' => esc_html__( 'On Tablet', 'gulir' ),
						'all'    => esc_html__( 'On Tablet & Mobile', 'gulir' ),
						'-1'     => esc_html__( 'Disable', 'gulir' ),
					],
					'std'     => '0',
				],
				[
					'id'   => 'design_entry_readmore',
					'name' => esc_html__( 'Read More', 'gulir' ),
					'tab'  => 'default-blog',
					'type' => 'info',
				],
				[
					'id'      => 'readmore',
					'name'    => esc_html__( 'Read More Button', 'gulir' ),
					'desc'    => esc_html__( 'Enable or disable the read more button.', 'gulir' ),
					'tab'     => 'default-blog',
					'type'    => 'select',
					'options' => gulir_config_tax_single_layouts(),
					'std'     => '0',
				],
				[
					'id'   => 'post_layout_info',
					'name' => esc_html__( 'Single Post Layout for This Category', 'gulir' ),
					'desc' => esc_html__( 'Select a layout for all single posts in this category. If a post belongs to multiple categories, the primary category or the first category\'s setting will apply.', 'gulir' ),
					'tab'  => 'post-template',
					'type' => 'info',
				],
				[
					'id'      => 'post_layout',
					'name'    => esc_html__( 'Single Post Layout', 'gulir' ),
					'desc'    => esc_html__( 'Select a predefined layout for single posts that belong to this category.', 'gulir' ),
					'info'    => esc_html__( 'This setting applies only to the standard post format. For all formats, use the "Use Ruby Template for Single Post Layout" setting below.', 'gulir' ),
					'tab'     => 'post-template',
					'single'  => true,
					'type'    => 'select',
					'options' => gulir_config_tax_single_layouts(),
					'std'     => '0',
				],
				[
					'id'          => 'post_template',
					'name'        => esc_html__( 'Use Ruby Template for Single Post Layout', 'gulir' ),
					'desc'        => esc_html__( 'Enter the Ruby template shortcode to assign it as the single post template for all posts in this category.', 'gulir' ),
					'info'        => esc_html__( 'This setting takes priority over the above settings and the Theme Options single layout settings, applying to all post formats. Leave blank to disable it.', 'gulir' ),
					'tab'         => 'post-template',
					'single'      => true,
					'type'        => 'textarea',
					'input_class' => 'ruby-template-input',
					'placeholder' => '[Ruby_E_Template id="1"]',
					'rows'        => 1,
					'std'         => '',
				],
			],
		];
	}
}

if ( ! function_exists( 'gulir_get_post_tag_config' ) ) {
	function gulir_get_post_tag_config() {

		return [
			'title'      => esc_html__( 'Gulir Tag Settings', 'gulir' ),
			'info'       => esc_html__( 'These settings will apply only to this tag and will take priority over other settings in "Theme Options > Tag Page and Archives."', 'gulir' ),
			'taxonomies' => [ 'post_tag' ],
			'id'         => 'gulir_category_meta',
			'tabs'       => [
				[
					'title' => esc_html__( 'Tag Colors', 'gulir' ),
					'id'    => 'entry-tax',
					'icon'  => 'dashicons-art',
				],
				[
					'title' => esc_html__( 'Featured Image', 'gulir' ),
					'id'    => 'tag-featured',
					'icon'  => 'dashicons-format-gallery',
				],
				[
					'title' => esc_html__( 'Tag Header', 'gulir' ),
					'id'    => 'tag-header',
					'icon'  => 'dashicons-editor-justify',
				],
				[
					'title' => esc_html__( 'Top Section', 'gulir' ),
					'id'    => 'top-section',
					'icon'  => 'dashicons-align-full-width',
				],
				[
					'title' => esc_html__( 'Listing Queries', 'gulir' ),
					'id'    => 'query',
					'icon'  => 'dashicons-database',
				],
				[
					'title' => esc_html__( 'Listing Template', 'gulir' ),
					'id'    => 'global-template',
					'icon'  => 'dashicons-admin-site',
				],
				[
					'title' => esc_html__( 'Site Header', 'gulir' ),
					'id'    => 'site-header',
					'icon'  => 'dashicons-heading',
				],
			],
			'fields'     => [
				[
					'id'   => 'highlight_color',
					'name' => esc_html__( 'Highlight Color', 'gulir' ),
					'desc' => esc_html__( 'Choose a highlight color for the entry icon. This applies if you replace post tags with entry category icons.', 'gulir' ),
					'info' => esc_html__( 'Default is global color.', 'gulir' ),
					'tab'  => 'entry-tax',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'color',
					'name' => esc_html__( 'Accent (Label) Color', 'gulir' ),
					'desc' => esc_html__( 'Select a color for the text label of the entry icon.', 'gulir' ),
					'tab'  => 'entry-tax',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'meta_color',
					'name' => esc_html__( 'Tag Text (for Entry Meta Bar / in Bold Style)', 'gulir' ),
					'desc' => esc_html__( 'Select a color for the tag text inside the post entry meta bar.', 'gulir' ),
					'info' => esc_html__( 'This color setting applies to tag in bold style (Theme Options > Theme Design > Entry Meta > Bold Style for Post Tag Meta) inside the meta bar (next to the author, date, reading time, etc.).', 'gulir' ),
					'tab'  => 'entry-tax',
					'css'  => 'bold-divider',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'dark_highlight_color',
					'name' => esc_html__( 'Dark Mode - Highlight Color', 'gulir' ),
					'desc' => esc_html__( 'Select a highlight color for the entry icon in dark mode.', 'gulir' ),
					'tab'  => 'entry-tax',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'dark_color',
					'name' => esc_html__( 'Dark Mode - Accent (Label) Color', 'gulir' ),
					'desc' => esc_html__( 'Select a color for the text label of the entry icon in dark mode.', 'gulir' ),
					'tab'  => 'entry-tax',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'dark_meta_color',
					'name' => esc_html__( 'Dark Mode - Tag Text (for Entry Meta Bar / in Bold Style)', 'gulir' ),
					'desc' => esc_html__( 'Select a color for the tag text inside the post entry meta bar for dark mode.', 'gulir' ),
					'tab'  => 'entry-tax',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'featured_image',
					'name' => esc_html__( 'Featured Image', 'gulir' ),
					'desc' => esc_html__( 'Upload featured images for this tag, these images will appear in all "Taxonomies List" blocks.', 'gulir' ),
					'tab'  => 'tag-featured',
					'type' => 'image',
				],
				[
					'id'   => 'header_style_info',
					'name' => esc_html__( 'Site Header', 'gulir' ),
					'desc' => esc_html__( 'Set up the website header (logo and navigation section) for this tag.', 'gulir' ),
					'tab'  => 'site-header',
					'type' => 'info',
				],
				[
					'id'      => 'header_style',
					'name'    => esc_html__( 'Site Header', 'gulir' ),
					'desc'    => esc_html__( 'Select a site header for this tag.', 'gulir' ),
					'tab'     => 'site-header',
					'type'    => 'select',
					'options' => gulir_config_header_style( true, true ),
					'std'     => '0',
				],
				[
					'id'          => 'header_template',
					'name'        => esc_html__( 'Or Use Ruby Template for Site Header', 'gulir' ),
					'desc'        => esc_html__( 'Input a Ruby Template shortcode for displaying as the website header for this tag.', 'gulir' ),
					'info'        => esc_html__( 'This setting will override all "Header Layout" settings. Leave it blank to disable.', 'gulir' ),
					'tab'         => 'site-header',
					'type'        => 'textarea',
					'input_class' => 'ruby-template-input',
					'placeholder' => '[Ruby_E_Template id="1"]',
					'rows'        => 1,
					'std'         => '',
				],
				[
					'id'   => 'archive_header_info',
					'name' => esc_html__( 'Category Header', 'gulir' ),
					'desc' => esc_html__( 'This section contains the post tags name and description, located below the site header.', 'gulir' ),
					'tab'  => 'tag-header',
					'type' => 'info',
				],
				[
					'id'      => 'archive_header',
					'name'    => esc_html__( 'Tag Header', 'gulir' ),
					'desc'    => esc_html__( 'Select a style for this tag header.', 'gulir' ),
					'tab'     => 'tag-header',
					'type'    => 'select',
					'options' => gulir_config_archive_header( true ),
					'std'     => '0',
				],
				[
					'id'      => 'breadcrumb',
					'name'    => esc_html__( 'Breadcrumb', 'gulir' ),
					'desc'    => esc_html__( 'Enable or disable the breadcrumb in this tag header.', 'gulir' ),
					'tab'     => 'tag-header',
					'type'    => 'select',
					'options' => [
						'0'  => esc_html__( '- Default -', 'gulir' ),
						'1'  => esc_html__( 'Use Global Setting', 'gulir' ),
						'-1' => esc_html__( 'Disable', 'gulir' ),
					],
					'std'     => '0',
				],
				[
					'id'      => 'pattern',
					'name'    => esc_html__( 'Background Pattern', 'gulir' ),
					'desc'    => esc_html__( 'Select a pattern style for the header background.', 'gulir' ),
					'tab'     => 'tag-header',
					'type'    => 'select',
					'options' => gulir_config_archive_header_bg( true ),
					'std'     => '0',
				],
				[
					'id'   => 'archive_top_section_info',
					'name' => esc_html__( 'Top Featured Section', 'gulir' ),
					'desc' => esc_html__( 'This section is located below the tag header and helps you build the top featured posts for this tag page. You can also create a custom tag header if you choose to disable the predefined one.', 'gulir' ),
					'tab'  => 'top-section',
					'type' => 'info',
				],
				[
					'id'          => 'template',
					'name'        => esc_html__( 'Template Shortcode', 'gulir' ),
					'desc'        => esc_html__( 'Input a "Ruby Template" shortcode to embed it after the tag header.', 'gulir' ),
					'info'        => esc_html__( 'It will display under the tag header, e.g. [Ruby_E_Template id="1"]', 'gulir' ),
					'tab'         => 'top-section',
					'type'        => 'textarea',
					'input_class' => 'ruby-template-input',
					'placeholder' => '[Ruby_E_Template id="1"]',
					'rows'        => 1,
					'std'         => '',
				],
				[
					'id'      => 'template_display',
					'name'    => esc_html__( 'Display Condition', 'gulir' ),
					'desc'    => esc_html__( 'Choose where the template should appear: on the first page only or on all pages.', 'gulir' ),
					'tab'     => 'top-section',
					'type'    => 'select',
					'options' => [
						'0' => esc_html__( '- Default -', 'gulir' ),
						'1' => esc_html__( 'Show in the first page', 'gulir' ),
						'2' => esc_html__( 'Show in all pages', 'gulir' ),
					],
					'std'     => '0',
				],
				[
					'id'          => 'posts_per_page',
					'name'        => esc_html__( 'Posts per Page', 'gulir' ),
					'desc'        => esc_html__( 'Enter the number of posts to display per page for this tag.', 'gulir' ),
					'info'        => esc_html__( 'This setting will apply to this category for both the Ruby Template and predefined layouts.', 'gulir' ),
					'tab'         => 'query',
					'placeholder' => '10',
					'type'        => 'text',
					'classes'     => 'small',
					'std'         => '',
				],
				[
					'id'          => 'template_global',
					'name'        => esc_html__( 'Use Ruby Template for the Post Listing', 'gulir' ),
					'desc'        => esc_html__( 'Insert a Ruby Template shortcode to set it as the main blog listing for this tag.', 'gulir' ),
					'info'        => esc_html__( 'Create a blog listing layout with Ruby Template via Elementor page builder and assign the template shortcode here to create your own layout.', 'gulir' ),
					'tab'         => 'global-template',
					'type'        => 'textarea',
					'input_class' => 'ruby-template-input',
					'placeholder' => '[Ruby_E_Template id="1"]',
					'rows'        => 1,
					'std'         => '',
				],
			],
		];
	}
}

if ( ! function_exists( 'gulir_register_default_term_settings' ) ) {
	function gulir_register_default_term_settings() {

		return [
			'title'  => esc_html__( 'Gulir Term Settings', 'gulir' ),
			'info'   => esc_html__( 'These settings apply only to this term, and the ones below will take priority over other settings in "Theme Options > Archives." The styling settings will only be available if you display the listing via Gulir Elementor blocks such as Grid, List, and Flex Block.', 'gulir' ),
			'id'     => 'gulir_category_meta',
			'tabs'   => [
				[
					'title' => esc_html__( 'Term Colors', 'gulir' ),
					'id'    => 'entry-tax',
					'icon'  => 'dashicons-art',
				],
				[
					'title' => esc_html__( 'Featured Image', 'gulir' ),
					'id'    => 'tax-featured',
					'icon'  => 'dashicons-format-gallery',
				],
				[
					'title' => esc_html__( 'Term Header', 'gulir' ),
					'id'    => 'tax-header',
					'icon'  => 'dashicons-editor-justify',
				],
				[
					'title' => esc_html__( 'Listing Queries', 'gulir' ),
					'id'    => 'query',
					'icon'  => 'dashicons-database',
				],
				[
					'title' => esc_html__( 'Listing Template', 'gulir' ),
					'id'    => 'global-template',
					'icon'  => 'dashicons-admin-site',
				],
				[
					'title' => esc_html__( 'Site Header', 'gulir' ),
					'id'    => 'site-header',
					'icon'  => 'dashicons-heading',
				],
			],
			'fields' => [
				[
					'id'   => 'highlight_color',
					'name' => esc_html__( 'Highlight Color', 'gulir' ),
					'desc' => esc_html__( 'Select a highlight color for the entry icon.', 'gulir' ),
					'info' => esc_html__( 'Default is global color.', 'gulir' ),
					'tab'  => 'entry-tax',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'color',
					'name' => esc_html__( 'Accent (Label) Color', 'gulir' ),
					'desc' => esc_html__( 'Select a color for the text label of the entry icon.', 'gulir' ),
					'info' => esc_html__( 'Default is white color.', 'gulir' ),
					'tab'  => 'entry-tax',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'meta_color',
					'name' => esc_html__( 'Term Name Text (for Entry Meta Bar)', 'gulir' ),
					'desc' => esc_html__( 'Select a color for the taxonomy text inside the post entry meta bar.', 'gulir' ),
					'info' => esc_html__( 'This color setting applies in the text-only layout inside the meta bar (beside the author, date, reading time, etc.).', 'gulir' ),
					'tab'  => 'entry-tax',
					'css'  => 'bold-divider',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'dark_highlight_color',
					'name' => esc_html__( 'Dark Mode - Highlight Color', 'gulir' ),
					'desc' => esc_html__( 'Select a highlight color for the entry icon in dark mode.', 'gulir' ),
					'tab'  => 'entry-tax',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'dark_color',
					'name' => esc_html__( 'Dark Mode - Accent (Label) Color', 'gulir' ),
					'desc' => esc_html__( 'Select a color for the text label of the entry icon in dark mode.', 'gulir' ),
					'tab'  => 'entry-tax',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'dark_meta_color',
					'name' => esc_html__( 'Dark Mode -  Term Name Text (for Entry Meta Bar)', 'gulir' ),
					'desc' => esc_html__( 'Select a color for the taxonomy text inside the post entry meta bar for dark mode.', 'gulir' ),
					'tab'  => 'entry-tax',
					'type' => 'color',
					'std'  => '',
				],
				[
					'id'   => 'featured_image',
					'name' => esc_html__( 'Featured Images', 'gulir' ),
					'desc' => esc_html__( 'Upload a featured image for this term, this image will appear in all "Taxonomies List" blocks.', 'gulir' ),
					'tab'  => 'tax-featured',
					'type' => 'image',
				],
				[
					'id'   => 'header_style_info',
					'name' => esc_html__( 'Site Header', 'gulir' ),
					'desc' => esc_html__( 'Set up the website header (logo and navigation section) for this term.', 'gulir' ),
					'tab'  => 'site-header',
					'type' => 'info',
				],
				[
					'id'      => 'header_style',
					'name'    => esc_html__( 'Site Header', 'gulir' ),
					'desc'    => esc_html__( 'Select a site header for this term.', 'gulir' ),
					'tab'     => 'site-header',
					'type'    => 'select',
					'options' => gulir_config_header_style( true, true ),
					'std'     => '0',
				],
				[
					'id'          => 'header_template',
					'name'        => esc_html__( 'Or Use Ruby Template for Site Header', 'gulir' ),
					'desc'        => esc_html__( 'Input a Ruby Template shortcode for displaying as the website header for this term.', 'gulir' ),
					'info'        => esc_html__( 'This setting will override all "Header Layout" settings. Leave it blank to disable.', 'gulir' ),
					'tab'         => 'site-header',
					'type'        => 'textarea',
					'input_class' => 'ruby-template-input',
					'placeholder' => '[Ruby_E_Template id="1"]',
					'rows'        => 1,
					'std'         => '',
				],
				[
					'id'   => 'tax_header_info',
					'name' => esc_html__( 'Term Header', 'gulir' ),
					'desc' => esc_html__( 'This section contains the term name and description, located below the site header.', 'gulir' ),
					'tab'  => 'tax-header',
					'type' => 'info',
				],
				[
					'id'      => 'archive_header',
					'name'    => esc_html__( 'Term Header', 'gulir' ),
					'desc'    => esc_html__( 'Select a style for this term header.', 'gulir' ),
					'tab'     => 'tax-header',
					'type'    => 'select',
					'options' => gulir_config_archive_header( true ),
					'std'     => '0',
				],
				[
					'id'      => 'breadcrumb',
					'name'    => esc_html__( 'Breadcrumb', 'gulir' ),
					'desc'    => esc_html__( 'Enable or disable the breadcrumb in this term header.', 'gulir' ),
					'tab'     => 'tax-header',
					'type'    => 'select',
					'options' => [
						'0'  => esc_html__( '- Default -', 'gulir' ),
						'1'  => esc_html__( 'Use Global Setting', 'gulir' ),
						'-1' => esc_html__( 'Disable', 'gulir' ),
					],
					'std'     => '0',
				],
				[
					'id'      => 'pattern',
					'name'    => esc_html__( 'Background Pattern', 'gulir' ),
					'desc'    => esc_html__( 'Select a pattern style for the header background.', 'gulir' ),
					'tab'     => 'tax-header',
					'type'    => 'select',
					'options' => gulir_config_archive_header_bg( true ),
					'std'     => '0',
				],
				[
					'id'          => 'posts_per_page',
					'name'        => esc_html__( 'Posts per Page', 'gulir' ),
					'desc'        => esc_html__( 'Input posts per page for this term.', 'gulir' ),
					'info'        => esc_html__( 'This setting will apply to this category for both the Ruby Template and predefined layouts.', 'gulir' ),
					'tab'         => 'query',
					'placeholder' => '10',
					'type'        => 'text',
					'classes'     => 'small',
					'std'         => '',
				],
				[
					'id'          => 'template_global',
					'name'        => esc_html__( 'Use Ruby Template for the Post Listing', 'gulir' ),
					'desc'        => esc_html__( 'Insert a Ruby Template shortcode to set it as the main blog listing for this term.', 'gulir' ),
					'info'        => esc_html__( 'Create a blog listing layout with Ruby Template via Elementor page builder and assign the template shortcode here to create your own layout.', 'gulir' ),
					'tab'         => 'global-template',
					'type'        => 'textarea',
					'input_class' => 'ruby-template-input',
					'placeholder' => '[Ruby_E_Template id="1"]',
					'rows'        => 1,
					'std'         => '',
				],
			],
		];
	}
}

if ( ! function_exists( 'gulir_register_term_settings' ) ) {
	/**
	 * @param $configs
	 *
	 * @return mixed
	 */
	function gulir_register_term_settings( $configs ) {

		$configs[] = gulir_get_category_config();
		$configs[] = gulir_get_post_tag_config();

		return $configs;
	}
}

add_filter( 'ruby_default_taxonomy', 'gulir_register_default_term_settings', 10, 1 );
add_filter( 'ruby_taxonomies', 'gulir_register_term_settings', 10, 1 );